### ISSUE TITLE
Single Command to run app (with watcher)

### ISSUE THREAD

**Issue by georgeedwards** [ericmdantas/generator-ng-fullstack#104]
@ericmdantas I think we talked about this over email. Having a single command to launch the app, rather than gulp and npm start. Ideally, with a watcher, to speed up the develop -> build -> test workflow by removing the build step. I believe the primary issue was not being able to run commands in parallel, just found [this](https://www.npmjs.com/package/concurrently). Would that do it?

**Comment by ericmdantas** [comment]
Awesome find!

I think both steps, `gulp` and `npm start`, should still exist separated, and then we could create something like: `npm run dev`, where it'd fire this module you just found.

What do you think?

**Comment by georgeedwards** [comment]
I completely agree, that we have it as well as the existing way of working. I a happy to do this after the authentication and Angular Material pieces.

**Comment by ericmdantas** [comment]
Right.

I'll leave it unassigned, then - whoever has got free time, implements it :smile:

**Comment by ericmdantas** [comment]
Remember to update the wiki.
