### ISSUE TITLE
duplicate "require-dir": "0.3.0"

### ISSUE THREAD

**Issue by dolanmiu** [ericmdantas/generator-ng-fullstack#107]
When I create a brand new project using this generator, there are two entries of "require-dir": "0.3.0", as shown in the screenshot below:

![screen shot 2016-04-08 at 06 33 11](https://cloud.githubusercontent.com/assets/2917613/14374949/f2edecfe-fd53-11e5-89cf-f4804416f5c1.png)

Please fix

**Comment by ericmdantas** [comment]
Thanks for pointing that out, @dolanmiu. I removed it.
