### ISSUE TITLE
Errors after gulp

### ISSUE THREAD

**Issue by BenevidesLecontes** [ericmdantas/generator-ng-fullstack#109]
Hello! I'm using ng-2 and i'm getting errors after gulp command, I already installed typings, express, express-content-length-validator:
<img width="1051" alt="screen shot 2016-04-16 at 8 29 43 pm" src="https://cloud.githubusercontent.com/assets/1839361/14584218/3c3503a6-0412-11e6-8a54-6138d833c757.png">

**Comment by ericmdantas** [comment]
Hello! This is being tracked in #79.
