### ISSUE TITLE
Generator: Component

### ISSUE THREAD

**Issue by ccocker** [ericmdantas/generator-ng-fullstack#121]
The yo ng-fullstack:component user --feature person generates components (html, ts & css) under one directory where the initial install has the components broken up into difference directories (templates, components, styles, services).

It would be good if the initial install todo example and the generator both used the same standards.

**Comment by ericmdantas** [comment]
Nice catch, @ccocker!

I'm on it.

**Comment by ericmdantas** [comment]
`1.7.13` released.
