### ISSUE TITLE
Generator: Server

### ISSUE THREAD

**Issue by ccocker** [ericmdantas/generator-ng-fullstack#122]
The generator yo ng-fullstack:endpoint skate --feature skateboard produces some errors.

For example: 

In the client.controller.ts file we are importing import clientDAO from '../dao/client.dao'; However the name of the file generated for the DAO is client-dao, not client.dao.

This same error occurs in each of the generated server files i.e. component, dao, route and model

**Comment by ericmdantas** [comment]
What server are you using?

**Comment by ccocker** [comment]
node

**Comment by ericmdantas** [comment]
`1.7.13` released.
