### ISSUE TITLE
Using Babel even when Typescript selected. 

### ISSUE THREAD

**Issue by netlander** [ericmdantas/generator-ng-fullstack#125]
Just started a project opting for Typescript but Babel is still a dependency and is being used as transpiler.

Why is that?

**Comment by ericmdantas** [comment]
It's only being used as a transpiler for gulp tasks, so you can do things like:

```js
import gulp from 'gulp';
import {server as karma} from 'karma';

@myAnnotation()
class MyClass {

}

// etc
```

**Comment by netlander** [comment]
Couldn't the above snipped have been achieved using Typescript? Just curious.

**Comment by ericmdantas** [comment]
Yeah, but you'd have to transpile your files to .js. With gulp 3.9.0~ you can use a gulpfile.babel.js to do it without explicitly transpiling.

**Comment by ericmdantas** [comment]
I'm closing this since it's the expected behaviour.

**Comment by netlander** [comment]
Yep. thanks for the clarification. Adding a star.

**Comment by ericmdantas** [comment]
Thanks! :smile:
