### ISSUE TITLE
Creating a new Angular2 Component does not place the feature name in the path to css + template

### ISSUE THREAD

**Issue by Tadimsky** [ericmdantas/generator-ng-fullstack#127]
In this file: generator-ng-fullstack/component/templates/component.ts

> @Component({
>   selector: '<%= name %>',
>   templateUrl: 'client/dev/<%= name %>/templates/<%= name %>.html',
>   styleUrls: ['client/dev/<%= name %>/styles/<%= name %>.css']
> })

There is no reference to the feature name in the path for the templateUrl and the styleUrls.

It should probably be something like this:

> @Component({
>   selector: '<%= name %>',
>   templateUrl: 'client/dev/<%= feature_name %>/<%= name %>/templates/<%= name %>.html',
>   styleUrls: ['client/dev/<%= feature_name %>/<%= name %>/styles/<%= name %>.css']
> })

Where feature_name is your variable for the feature name :)

**Comment by ericmdantas** [comment]
On it.

**Comment by ericmdantas** [comment]
Released `1.7.16`.

**Comment by Tadimsky** [comment]
Awesome, thanks Eric!

**Comment by ericmdantas** [comment]
Thanks for reporting it :smile:
