### ISSUE TITLE
Generating a new resource in an Angular2 project creates an Angular1 resource file

### ISSUE THREAD

**Issue by Tadimsky** [ericmdantas/generator-ng-fullstack#128]
It seems like there is no template for an angular2 resource file.
It instead uses this and creates an angular1 resource.

`generator-ng-fullstack/resource/templates/resource.js`

**Comment by ericmdantas** [comment]
Hello, @Tadimsky.

Resource is not part of Angular2 wrapper, and last time I checked, they didn't intend in having one. The only things Angular2 and Angular1 share are:

- Directives;
- Services;
- Factories;
- Models;
- Views;
- Styles;

Filters, Resources, Delegators, etc are all part of Angular 1 only.

What we could have is a warning maybe? Something like: "There's no such thing in Angular2".

**Comment by Tadimsky** [comment]
Ok, that's good to know - thanks!
I was using it for things like config files, etc.

But yeah, it would be good to not create it then for Angular2 I think.

**Comment by ericmdantas** [comment]
Cool, I'll try to solve it today and release a patch.

**Comment by ericmdantas** [comment]
I'll leave it for `1.8`.

**Comment by ericmdantas** [comment]
This is closed in `v1.8` branch.
