### ISSUE TITLE
Cordova support

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#129]
As spoken to @bernardbr, it'd be nice to have some things to facilitate the development for cordova. 

Things that would need to change:

- paths would have to begin with `./somewhere` instead of `somewhere`;
- location/routes would have to use `#`;
- generate an empty file called cordova.js in `client/dev` and reference it in `index.html`.

@bernardbr, what else?

**Comment by bernardbr** [comment]
Sounds great!

It is also necessary to add this meta in index.html:

```html
    <meta http-equiv="Content-Security-Policy" content="default-src *; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'; media-src *; img-src * data:;">
```

And also prefix the files path of scripts and css with "./", such as:

```html
<script type="text/javascript" src="./app.login.js?rev=@@hash"></script>
```

**Comment by ericmdantas** [comment]
:+1:

**Comment by georgeedwards** [comment]
If mobile dev is of interest, I'd suggest taking a look at [NativeScript](www.nativescript.org/), it's open source, runs JS natively much more performantly and works well with Angular 2.

**Comment by bernardbr** [comment]
Thanks @georgeedwards! I didn't know NativeScript... Sounds good. I will study it!

**Comment by georgeedwards** [comment]
I would certainly recommend it, [this](https://github.com/NathanWalker/angular2-seed-advanced) is an interesting seed project, where you can target ios, android, OSX, Windows and Linux desktops and mobiles, with a single JS code base. It uses Nativescript and Electron, so that shows how versatile Nativescript code can be.

**Comment by ericmdantas** [comment]
Added some tips for cordova with some comments and stuff (c04a646). Let's see how it goes, if people get interested, we can have a specific option to do it.

For now, the comments might do.

Releasing `1.8`.

**Comment by ericmdantas** [comment]
Actually, I'll do it only for Angular1.x. Gotta figure out what to do with Angular2 and the `node_modules` deps.

**Comment by ericmdantas** [comment]
Created question: "'Are you using Cordova (for mobile development)?". 

Such quesiton will only show up if the user chose a `client only app` and `ng1` - `ng2` is not supported yet.

**Comment by ericmdantas** [comment]
`1.8` should be out tonight.
