### ISSUE TITLE
When the generator is set to HTTP 1.1, it'd be nice to have an additional option to set if files (css and js) will be concatenated on build-dist.

### ISSUE THREAD

**Issue by bernardbr** [ericmdantas/generator-ng-fullstack#130]
@ericmdantas , what do you think about this?

**Comment by ericmdantas** [comment]
Sounds good.

**Comment by ericmdantas** [comment]
I'm leaning towards having the files concatenated, like `lib_bundle_13jdhs.js` and `src_bundle_12313.js` and let the user choose how it'll be grouped.
