### ISSUE TITLE
Node.js Endpoint Generator not building the schema correctly.

### ISSUE THREAD

**Issue by Tadimsky** [ericmdantas/generator-ng-fullstack#132]
Generated code:
> "use strict";
> 
> const mongoose = require('mongoose');
> 
> const _userSchema = {
>   somethingSomething: {type: String, required: true, trim: true},
>   createdAt: {type: Date, default: Date.now}
> }
> 
> module.exports = mongoose.Schema(userSchema);

This should be module.exports = mongoose.Schema(**_userSchema**);

**Comment by ericmdantas** [comment]
Thanks for pointing it out.

`1.7.17` released.
