### ISSUE TITLE
  message: 'connect ECONNREFUSED 127.0.0.1:27017

### ISSUE THREAD

**Issue by gilbertlucas46** [ericmdantas/generator-ng-fullstack#134]
An error ocurred with the DB connection:  { [MongoError: connect ECONNREFUSED 127.0.0.1:27017]
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017' }

**Comment by ericmdantas** [comment]
Hello, @gilbertlucas46.

Make sure you run `mongod` before starting your application.
