### ISSUE TITLE
Do not serve files from root

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#135]
Instead of serving stuff from the root, only serve files necessary for the application, which will be in: `node_modules` (for ng2), `client/dev` and `client/dist`.

Spoken to @matthewharwood.

**Comment by ericmdantas** [comment]
Added for 1.8 because it will break some paths people are using right now.

**Comment by ericmdantas** [comment]
fixed in `1.8` branch.

**Comment by ericmdantas** [comment]
Should be fixed with: 5adcae1.

**Comment by Tadimsky** [comment]
Hey @ericmdantas - is there any good way to upgrade a project built with an older version to use the new layout you have in 1.8?

**Comment by ericmdantas** [comment]
It should be just find and replace. All the files in client/dev instead of going all the way from the root to get something, should just try to get it locally. For example:

-  Before: `templateUrl: "client/dev/todo/templates/todo.html"`;
- After: "todo/templates/todo.html".

Same thing for index.html, which would get stuff from root + somewhere, now it should either find the folder directly in node_modules or client/dev (no need to specify the latter).

As for the server change, just go to the file responsible for the static serving and change serving directly from the root, to serve from `node_modules` instead.
