### ISSUE TITLE
Core contributors

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#14]
Hello, guys!

As discussed in DaftMonk/generator-angular-fullstack/issues/884, I'd like to open an organization and make things move forward. Right now, what I have here was based on my needs when I created - there's nothing written in stone - feel free to be creative.

[Bring in some ideas](1), good or bad, we'll discuss it all!

As for this issue, I'd like to know who I can count with for the core team. Of course we won't have all the time to create/fix stuff, but I believe we can do great things.

cc: @honkskillet, @justingreenberg, @jgodi, @Toub, @dmarcelino, @remicastaing, @khwerhahn

PS: Let me know if there's someone else who might be interested in helping =]

**Comment by Toub** [comment]
I would like to start talking about the following topics:
* directory structure (e.g. server & client clear separation, naming conventions, no duplicate names)
* coding best practices (e.g. based on https://github.com/johnpapa/angular-styleguide)
* gulp (core task, split configuration in several files, best practices)

We should open issues for theses topic and fix them before starting more complex tasks.

**Comment by ericmdantas** [comment]
[Gulp task issue is right here](6)

@jgodi said he'd give a hand with the best practices based on jhon papa's styleguides.

About the directory structure, do you see something that should be changed or do you mean to document the way modifications should be made? Or both?

**Comment by jgodi** [comment]
Yes, I will comb through the client side code and get it up to terms with the style guide. Should be done soon :)

I do agree that splitting of the gulp tasks would be nice. More so, I would like to see a `gulp.config.js` where all the paths/files/settings are defined that are pulled into the gulp tasks. That way users have a one stop shop to change config rather then hunting down into task files.

**Comment by Toub** [comment]
> About the directory structure, do you see something that should be changed or do you mean to document the way modifications should be made? Or both?

I created a separated issue about this topic:  #15 (Directory structure)

**Comment by ericmdantas** [comment]
Alright, just created the organization: [nxgen](https://github.com/nxgen).

Nothing there yet, just waiting on who's willing to contribute so I can add you there and move this repo.

:smile:

**Comment by jgodi** [comment]
Perfect. When I get more free time I will be a regular contributor :)

**Comment by ericmdantas** [comment]
@jgodi, good to hear! =]

Also, noted about the server, should not be hard to separate things, but we'll have to sort the gulp tasks first, so client tasks won't mix with server tasks and suchs. I'm stuck with go integration for now, but I'm keeping an eye on it.

**Comment by remicastaing** [comment]
How about to have a dedicated gitter for this generator?

**Comment by ericmdantas** [comment]
@remicastaing, [there you go](https://gitter.im/ericmdantas/generator-ng-fullstack) :smile:

**Comment by remicastaing** [comment]
Wouldn't be good to have a repository with a generated app to discuss about
the result and about the generator?

**Comment by jgodi** [comment]
We can use the gh-pages branch for that possibly.

**Comment by dmarcelino** [comment]
I would love to get @kingcody's feedback on this as he is quite active on generator-angular-fullstack and may bring some interesting ideas to this in addition to expertise.

**Comment by ericmdantas** [comment]
Closing this. Better discuss in separate issues.
