### ISSUE TITLE
a lot of ts compile errors

### ISSUE THREAD

**Issue by aaronchen2k** [ericmdantas/generator-ng-fullstack#146]
aaron-mac:testspace aaron$ npm run watch

 testspace@0.0.1 watch /Users/aaron/tinypace/code/testspace
 gulp

[21:22:27] Requiring external module babel-register
[21:22:29] Using gulpfile ~/tinypace/code/testspace/gulpfile.babel.js
[21:22:29] Starting 'client.build_ts'...
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/directives/ng_class.d.ts(72,35): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/forms/directives/select_control_value_accessor.d.ts(18,17): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/pipes/async_pipe.d.ts(29,29): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/pipes/async_pipe.d.ts(35,38): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/pipes/async_pipe.d.ts(37,39): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/common/src/pipes/async_pipe.d.ts(39,44): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/directive_normalizer.d.ts(10,62): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/directive_normalizer.d.ts(11,95): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/offline_compiler.d.ts(32,70): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/offline_compiler.d.ts(34,85): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/output/output_ast.d.ts(417,63): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/runtime_compiler.d.ts(28,44): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/selector.d.ts(51,25): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/selector.d.ts(53,24): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/template_parser.d.ts(37,12): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/view_compiler/compile_view.d.ts(41,16): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/view_compiler/compile_view.d.ts(43,13): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/view_resolver.d.ts(10,13): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/src/xhr.d.ts(6,23): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/test_component_builder.d.ts(77,19): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/test_component_builder.d.ts(89,25): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/test_component_builder.d.ts(91,26): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/test_component_builder.d.ts(93,25): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/test_component_builder.d.ts(95,29): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/test_component_builder.d.ts(97,21): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/test_component_builder.d.ts(176,43): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/view_resolver_mock.d.ts(5,13): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/view_resolver_mock.d.ts(7,23): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/view_resolver_mock.d.ts(9,17): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/view_resolver_mock.d.ts(11,26): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/compiler/testing/xhr_mock.d.ts(10,23): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/application_ref.d.ts(39,88): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/application_ref.d.ts(99,42): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/application_ref.d.ts(174,33): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(26,16): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/di/reflective_provider.d.ts(105,123): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/di/reflective_provider.d.ts(105,165): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/async.d.ts(27,33): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/async.d.ts(28,45): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(100,41): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(101,22): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/collection.d.ts(102,25): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/lang.d.ts(4,17): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/lang.d.ts(5,17): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/lang.d.ts(70,59): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(2,14): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(11,50): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/linker/component_resolver.d.ts(8,53): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/linker/component_resolver.d.ts(12,44): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(62,148): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(103,144): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(108,139): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/linker/dynamic_component_loader.d.ts(109,135): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/reflection/reflector.d.ts(28,22): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/reflection/reflector.d.ts(30,15): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/reflection/reflector.d.ts(32,15): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/reflection/reflector.d.ts(34,15): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/reflection/reflector.d.ts(36,16): error TS2304: Cannot find name 'Set'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/src/testability/testability.d.ts(40,20): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/core/testing/mock_application_ref.d.ts(12,33): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/http/src/headers.d.ts(29,18): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/http/src/headers.d.ts(45,59): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/http/src/url_search_params.d.ts(11,16): error TS2304: Cannot find name 'Map'.
/Users/aaron/tinypace/code/testspace/node_modules/@angular/platform-browser-dynamic/platform_browser_dynamic.d.ts(75,90): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
/Users/aaron/tinypace/code/testspace/node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.
tests/client/todo/components/todo-cmp_test.ts(1,1): error TS6053: File '/Users/aaron/tinypace/code/testspace/typings/main.d.ts' not found.
tests/client/todo/components/todo-cmp_test.ts(65,9): error TS2304: Cannot find name 'spyOn'.
tests/client/todo/services/todo-service_test.ts(1,1): error TS6053: File '/Users/aaron/tinypace/code/testspace/typings/main.d.ts' not found.
[21:22:33] TypeScript: 107 semantic errors
[21:22:33] TypeScript: emit succeeded (with errors)
[21:22:33] Finished 'client.build_ts' after 3.79 s
[21:22:33] Starting 'client.watch'...
[21:22:33] Finished 'client.watch' after 60 ms
[21:22:33] Starting 'default'...
[21:22:33] Finished 'default' after 23 μs

**Comment by kamiranoff** [comment]
that is how I fixed it.
Adding this line in index.ts :
/* Avoid: 'error TS2304: Cannot find name <type>' during compilation */
///<reference path="../../typings/browser/ambient/es6-shim/index.d.ts"/>

**Comment by aaronchen2k** [comment]
I am not very clear about, just add "///" on the top of index.ts?
Thanks

**Comment by kamiranoff** [comment]
I am sorry I added this line after the tripple slash
<reference path="../../typings/browser/ambient/es6-shim/index.d.ts"/>
I edided my comment above, you should see the complete line

**Comment by kamiranoff** [comment]
Sorry I edited the comment above. That is what follows the tripple slash
`<reference path="../../typings/browser/ambient/es6-shim/index.d.ts"/>`

**Comment by aaronchen2k** [comment]
Got it , but there is no ../../typings folder, thanks

**Comment by kamiranoff** [comment]
I am not sure how it is generated. Maybe by doing 'typings install' or 'tsc' in the console

**Comment by kamiranoff** [comment]
I double checked you have to type `typings install` to generate the typings folder

**Comment by aaronchen2k** [comment]
It works well, thanks a lot!

BTW, can we remove the last error "unresolved function or method map()" in idea ide for below codes?
`  getAll():Observable<any> {
    return this._http
               .get(TodoService.ENDPOINT.replace(':id', ''))
               .map((r) => r.json());
  }`

**Comment by ericmdantas** [comment]
Thanks for the help, @kamiranoff!
