### ISSUE TITLE
Typescript definition file question

### ISSUE THREAD

**Issue by joshrouwhorst** [ericmdantas/generator-ng-fullstack#149]
I have a d.ts file that I'm trying to use with a JS library. It's not available to install through typings or tsd so I'm trying to manually add these files. 

I added a `///<reference>` tag at the head of the TS files using this library. My IDE recognizes the reference and when I run `npm run dev` the build process is recognizing the reference. But when the page comes up in the browser the JS library isn't getting loaded and I get reference errors.

What would be the right way to add a d.ts file and JS library?

I'm still getting familiarized with TS and I'd appreciate any help. Thanks!

**Comment by ericmdantas** [comment]
Hello, @joshrouwhorst.

To make this new dependency loaded you'll have to add it to the file in `client/dev/config.js` the following:

```
 map: {
    lodash: 'node_modules/lodash/lodash.js'
 }
```

And then:

```ts
import _ from 'lodash';

console.log('lodash version:', _.VERSION);
```

This link explains it better: http://stackoverflow.com/questions/34660265/importing-lodash-into-angular2-typescript-application

**Comment by joshrouwhorst** [comment]
Thanks for getting back to me! 

Unfortunately the version of the library I'm using (BabylonJS 2.4 beta) isn't released to npm yet. I tried your suggestion using map in the config.js file to point to the JS file but `npm run dev` still didn't import it into the page. I ended up just manually adding a script tag to index.html and that did the trick.

**Comment by ericmdantas** [comment]
:+1:
