### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by Toub** [ericmdantas/generator-ng-fullstack#15]
I open a new issue from the discussion started in #14 (Core contributors)

> About the directory structure, do you see something that should be changed or do you mean to document the way modifications should be made? Or both?

Well, both ;-)

A few suggestions to consider (just some ideas, a base for discussions):
* some files on server and client side have the same name, and it is a pain when you want to open files by name in your editor (e.g. todo.model.js, todo.dao.js)
* todo.js contains the controller but is named todo.js (not explicit)
* tests are separated from server and clients, is it a good idea? (look at the structure generated by https://github.com/Swiip/generator-gulp-angular)
* why to have sub-folders with only one file inside when the file name is already explicitly named? we could have todo.controller.js, todo.model.js, todo.dao.js and todo.routes.js immediately in todo folder
* it would be nice to organize the angular application by module, so we would create a file todo.module.js
* could we consider to use [https://github.com/js-data/js-data] instead of ngresource - it is an data abstraction layer, very flexible (this should be discussed in a dedicated issue)
* imgs folder is not usual, what about img or images ?

A client module could be composed of several pages/directives/filters, so the directory structure could be flat:

   client/(dev)/modules/todo/todo.module.js

   client/(dev)/modules/todo/todo.model.js
   client/(dev)/modules/todo/todoHistory.model.js
   
   client/(dev)/modules/todo/todo.view.page.ctrl.js
   client/(dev)/modules/todo/todo.view.page.html
   client/(dev)/modules/todo/todo.view.page.scss
   
   client/(dev)/modules/todo/todo.edit.page.ctrl.js
   client/(dev)/modules/todo/todo.edit.page.html
   client/(dev)/modules/todo/todo.edit.page.scss
   
   client/(dev)/modules/todo/todo-autocomplete.directive.js
   client/(dev)/modules/todo/todo-autocomplete.directive.html
   client/(dev)/modules/todo/todo-autocomplete.directive.scss
   
    client/(dev)/modules/todo/todo-formatter.filterjs

For small modules, a flat hierarchy could be enough, but if the module is growing, we can split it in submodules:

    client/(dev)/modules/todo/todo-list/view
    client/(dev)/modules/todo/todo-list/edit
    client/(dev)/modules/todo/todo/view
    client/(dev)/modules/todo/todo/edit
    client/(dev)/modules/todo/todo-history-view

or group the files by types:

    client/(dev)/modules/todo/entities
    client/(dev)/modules/todo/pages
    client/(dev)/modules/todo/directives
    client/(dev)/modules/todo/filters

Of course, the best would be to let the user decide, so gulp would just detect the file in the subfolders whatever their names (".module.js" file being loaded first).

Is client/dev a good name? Is not client/src better ? Or just client ?

**Comment by ericmdantas** [comment]
> some files on server and client side have the same name, and it is a pain when you want to open files by name in your editor (e.g. todo.model.js, todo.dao.js)

I'm aware of this one, but I just couldn't find anything better to name it. Maybe suffix, preffix with client/server?

> todo.js contains the controller but is named todo.js (not explicit)

That's actually the syntax for the new angular router, it's pretty strict for that. When I tested it, if it had a different name, angular wouldn't find the file. [See](http://blog.thoughtram.io/angularjs/2015/02/19/futuristic-routing-in-angular.html).

> tests are separated from server and clients, is it a good idea? (look at the structure generated by https://github.com/Swiip/generator-gulp-angular)

That's a tricky one. Since we are separating by feature on the client side, it'd be easy to add ```_test.js``` to each feature/type and when running gulp, just don't get these files.

But what about server? Would we have to have a dist folder for the server too? I believe DaftMonk's generator does that. I'll check this other generator you mentioned.

> it would be nice to organize the angular application by module, so we would create a file todo.module.js

Agreed, with the separation by feature, that's almost a must.

> js-data

Never heard of it, gonna take a look later today. Feel free to open the issue, though =]

> imgs folder is not usual, what about img or images ?

Looks like I got in the middle of the way :smile: 


About the structure fight: flat vs complex vs flexible. I'm thinking about a way to have something like:

```
$ yo ng-fullstack:controller --feature user --path something/goes/here
``` 

And we could use such path to create the new file.


About the ```client/dev```, ```client/__tmp``` and ```client/dist```, I have my doubts if that's the best way to approach it, but since you'll be developing in one structure (dev), having files compiled to another (__tmp with less, concatenated js, etc) and the dist folder with it all together, plus the uglifications and everything else, for me it feels right - I'm open for suggestions, though.

**Comment by jgodi** [comment]
I will be making the client side code conform to [John Papa's Style Guide](https://github.com/johnpapa/angular-styleguide/blob/master/README.md), which has the client side directory structure defined. We can use that as a base.

As for the tests mixed in with the client side code, I personally prefer it. While you are working on a controller your test is right there and easy to update and work with. This is easily handled via gulp to only inject files needed for dev/prod (tests will have the `*.spec.js` file names or something similar):

```
 src + '/**/*.js',
 '!' + src + '/**/*.spec.js',
```

**Comment by ericmdantas** [comment]
@jgodi, sounds good!

My only doubt is the server code, would we need to have a ```dist``` folder for the server too? Because it doesn't feel right to have ```src code```  and ```test code``` side by side in production.

**Comment by Toub** [comment]
What about?

/src/client
/src/server

/dist/client
/dist/server

/.tmp/...

**Comment by ericmdantas** [comment]
> /src/client
/src/server

>/dist/client
/dist/server

>/.tmp/...

And then gulp would take care of transpiling/building/hinting/etc both the client and server code. I think that's ideal.

**Comment by jgodi** [comment]
They wouldn't be side-by-side in production, only in development. Our `gulp` task to build the dist version of the application will ignore all test files. 

As for the packages, I like that approach.

**Comment by ericmdantas** [comment]
@jgodi, yeah @Toub's suggestion solves the production thing.

As for the extension for the tests, I prefer ```_test.js```, but that might just be me.

**Comment by ericmdantas** [comment]
Also, I think we should hold this one a bit until we have #6 finished, or at least separated enough.

**Comment by ericmdantas** [comment]
As of now, we've got the following structure:

Angular 1:

```
client/dev/{feature}/controllers/{name}.js
client/dev/{feature}/directives/{name}.js
client/dev/{feature}/services/{name}.js
client/dev/{feature}/decorators/{name}.js
client/dev/{feature}/resources/{name}.js
client/dev/{feature}/models/{name}.js
client/dev/{feature}/filters/{name}.js
client/dev/{feature}/factory/{name}.js
client/dev/{feature}/templates/{name}.html
client/dev/{feature}/styles/{name}.css
```

Angular 2:

```
client/dev/{feature}/components/{name}.ts
client/dev/{feature}/directives/{name}.ts
client/dev/{feature}/services/{name}.ts
client/dev/{feature}/factory/{name}.ts
client/dev/{feature}/models/{name}.ts
client/dev/{feature}/pipes/{name}.ts
client/dev/{feature}/templates/{name}.html
client/dev/{feature}/styles/{name}.css
```

Node Server:

```
server/api/{feature}/controllers/{name}.js
server/api/{feature}/dao/{name}.js
server/api/{feature}/models/{name}.js
server/api/{feature}/routes/{name}.js
```

Go Server:

```
server/api/{feature}/controller/{name}.go
server/api/{feature}/dao/{name}.go
server/api/{feature}/model/{name}.go
server/api/{feature}/routes/{name}.go
```
