### ISSUE TITLE
Dart Support

### ISSUE THREAD

**Issue by MaxMansfield** [ericmdantas/generator-ng-fullstack#150]
It would be amazing if you added dart support for Angular2

Let me know if I can help.

**Comment by ericmdantas** [comment]
Hello, @MaxMansfield! Thanks for the suggestion.

I have never worked with Dart, but it does sound like a good addition to the client stack. 

Probably the best way to get it started is: you, or someone else experienced in Dart, send a PR with the base for the todo app (src/tests).

After doing that, we can think about the wiki and the explanations on setup, build and this kind of things that *may* be different for Dart.

**Comment by MaxMansfield** [comment]
The issue with using Dart and Angular2 is that the API changes way too much right now and there is little to no documentation. 

The idiomatic way is no longer the correct way and vica versa. I'm going to wait until they finalize the dart api if that's cool with you. Packages aren't even where they used to be and there is no accurate docs for it right now.

**Comment by ericmdantas** [comment]
Yeah, I played a bit with Dart since you opened the issue and even though I liked, I had the feeling some stuff were really missing.

I'll add the support for Dart when the API is stable enough. Feel free to ping me if I miss anything.

**Comment by ericmdantas** [comment]
Out of scope.
