### ISSUE TITLE
Fresh install give error on gulp and npm start

### ISSUE THREAD

**Issue by TejasCMehta** [ericmdantas/generator-ng-fullstack#153]
`$ npm start`
`$ npm run watch`

![image](https://cloud.githubusercontent.com/assets/5519037/15746466/467714ba-28f4-11e6-8349-bc04ac3ad342.png)

![image](https://cloud.githubusercontent.com/assets/5519037/15746479/61c4f836-28f4-11e6-92db-01779ce76c53.png)

`tsc` command gives below error

![image](https://cloud.githubusercontent.com/assets/5519037/15746517/911ec206-28f4-11e6-91d3-f15e42434014.png)

App starts on `gulp run watch` and also works but so many errors in console.

Please guide!!

**Comment by ericmdantas** [comment]
Hello, @TejasCMehta.

Make sure you run `typings install` before doing anything else.

**Comment by ericmdantas** [comment]
Closing as dup of https://github.com/ericmdantas/generator-ng-fullstack/issues/146.

**Comment by TejasCMehta** [comment]
@ericmdantas  Thanks for quick help!!

**Comment by ericmdantas** [comment]
No problem! :smile:
