### ISSUE TITLE
Bower depencies

### ISSUE THREAD

**Issue by remicastaing** [ericmdantas/generator-ng-fullstack#16]
I'm opening this issue to gather some dependencies consideration:
- [js-data](https://github.com/js-data/js-data) instead of ngresource - it is an data abstraction layer, very flexible (proposed by @Toub)
- [a0-angular-storage](https://github.com/auth0/angular-storage) instead of ngCookie: uses localStorage by default, Lets you save JS Objects, etc.
- [angulartics](https://github.com/luisfarzati/angulartics) for full path tracking with Google Analytics
- angular-messages

**Comment by ericmdantas** [comment]
Hello, @remicastaing.

> js-data

I still have to take a look at it, but it seems promising.

> a0-angular-storage

For now, I think [ng-xtorage](https://github.com/ericmdantas/ng-xtorage) there might do the trick for storage. I works for local/sessionStorage, [forms](https://github.com/ericmdantas/ng-xtorage-form) and it also has a module [helper for expiration](https://github.com/ericmdantas/ng-xtorage-expiration).

> angulartics

Looks good, gonna try that one later.

> angular-messages

That's already there, not being used on the todo yet, I guess.

Gonna keep this one open for more ideas and points.

**Comment by Toub** [comment]
I already use js-data on several projects so I can help with that one.

**Comment by ericmdantas** [comment]
We'd be better use the [angular wrapper](https://github.com/js-data/js-data-angular), right?

**Comment by ericmdantas** [comment]
Just watched the [video about js-data](https://www.youtube.com/watch?v=8wxnnJA9FKw) by its creator. Seems really nice indeed. I'd love the help, @Toub.

The thing we have to keep in mind is that the user of this generator will choose between ```io.js (javascript)``` on the backend or ```go (golang)```. So, we might still have ```ngResource``` or something similar floating around (when the user chooses ```go server``` instead of ```io.js server```.

Or have js-data to work without knowing anything about the server? I don't know the pros and cons of that, you could tell better.

**Comment by ericmdantas** [comment]
About angulartics:

Do I still have to have this in my html?

```html

<script>
       (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
       (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
       m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
       })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

       ga('create', 'UA-XXXXX-X');
       ga('send', 'pageview');
</script>

```

Or the module will take care of it?

**Comment by jgodi** [comment]
You will still need that, just take the 

```
ga('send', 'pageview');
```
part out of it since that library will take care of sending page views.

**Comment by Toub** [comment]
I created a new ticket for js-data: "Replace ngResource by js-data model layer" #19

**Comment by ericmdantas** [comment]
@jgodi, alright. Gonna do that later today [#22](22).

@Toub, good idea - that's a big issue by itself.

**Comment by ericmdantas** [comment]
Closing this one, most things have been taken care of.
