### ISSUE TITLE
new install - error on npm run

### ISSUE THREAD

**Issue by adskiremote** [ericmdantas/generator-ng-fullstack#162]
Hi after installing I run npm run dev and I get a tonne of errors.
Here's a list of the output.  Can someone help me find how to fix these?

`> tsc && concurrently "npm start" "gulp"

server/api/todo/controller/todo-controller.ts(1,26): error TS2307: Cannot find module 'express'.
server/api/todo/dao/todo-dao.ts(1,27): error TS2307: Cannot find module 'mongoose'.
server/api/todo/dao/todo-dao.ts(2,26): error TS2307: Cannot find module 'bluebird'.
server/api/todo/dao/todo-dao.ts(3,20): error TS2307: Cannot find module 'lodash'.
server/api/todo/model/todo-model.ts(1,27): error TS2307: Cannot find module 'mongoose'.
server/api/todo/routes/todo-routes.ts(3,26): error TS2307: Cannot find module 'express'.
server/commons/static/index.ts(3,26): error TS2307: Cannot find module 'express'.
server/commons/static/index.ts(4,21): error TS2307: Cannot find module 'fs'.
server/commons/static/index.ts(8,19): error TS2304: Cannot find name 'process'.
server/config/db.conf.ts(3,27): error TS2307: Cannot find module 'mongoose'.
server/config/db.conf.ts(4,15): error TS2304: Cannot find name 'require'.
server/config/db.conf.ts(8,20): error TS2304: Cannot find name 'process'.
server/config/db.conf.ts(8,61): error TS2304: Cannot find name 'process'.
server/config/routes.conf.ts(3,26): error TS2307: Cannot find module 'express'.
server/config/routes.conf.ts(4,25): error TS2307: Cannot find module 'morgan'.
server/config/routes.conf.ts(5,29): error TS2307: Cannot find module 'body-parser'.
server/config/routes.conf.ts(6,25): error TS2307: Cannot find module 'helmet'.
server/config/routes.conf.ts(10,21): error TS2304: Cannot find name 'process'.
server/config/routes.conf.ts(12,29): error TS2304: Cannot find name 'process'.
server/routes/index.ts(1,26): error TS2307: Cannot find module 'express'.
server/server.ts(1,1): error TS6053: File 'typings/index.d.ts' not found.
server/server.ts(5,22): error TS2304: Cannot find name 'process'.
server/server.ts(6,5): error TS2304: Cannot find name 'require'.
server/server.ts(8,12): error TS2304: Cannot find name 'process'.
server/server.ts(10,26): error TS2307: Cannot find module 'express'.
server/server.ts(11,21): error TS2307: Cannot find module 'os'.
server/server.ts(12,24): error TS2307: Cannot find module 'https'.
server/server.ts(13,21): error TS2307: Cannot find module 'fs'.
server/server.ts(25,24): error TS2304: Cannot find name '__dirname'.
server/server.ts(26,25): error TS2304: Cannot find name '__dirname'.
server/server.ts(32,35): error TS2304: Cannot find name 'process'.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.4
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! xxx@0.0.1 dev: `tsc && concurrently "npm start" "gulp"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the xxx@0.0.1 dev script 'tsc && concurrently "npm start" "gulp"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xxxpackage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm start" "gulp"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xxx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xxx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxx\Documents\App Projects\xxx\npm-debug.log`

**Comment by ericmdantas** [comment]
Hello, @adskiremote.

Please run `typings install` and `tsc` and let me know how it goes.

**Comment by adskiremote** [comment]
less errors but still have one.

Here's the output after running npm run dev

`C:\Users\xxx\Documents\App Projects\xxx>npm run dev

> xxx@0.0.1 dev C:\Users\xxx\Documents\App Projects\xxx
> tsc && concurrently "npm start" "gulp"

error TS5023: Unknown compiler option 'moduleResolution'.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v4.4.4
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! xxx@0.0.1 dev: `tsc && concurrently "npm start" "gulp"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the xxx@0.0.1 dev script 'tsc && concurrently "npm start" "gulp"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the xxx package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm start" "gulp"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs xxx
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls xxx
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\xxx\Documents\App Projects\xxx\npm-debug.log`

**Comment by ericmdantas** [comment]
That's weird. What does it say when you run `tsc --version`?

**Comment by adskiremote** [comment]
It says: 3.5.3

**Comment by ericmdantas** [comment]
Well, there's something wrong then. Because the latest version is `1.8.10`.

Try doing the following:
- run `npm i -g typescript`
- run `tsc` (there should be no errors)
- run `npm run dev`

**Comment by adskiremote** [comment]
odd - when running tsc I get errors.

It successfully installs typescript - version 1.8.10

Then running tsc I get these errors.

server/api/todo/controller/todo-controller.ts(1,26): error TS2307: Cannot
find module 'express'.
server/api/todo/dao/todo-dao.ts(1,27): error TS2307: Cannot find module
'mongoose'.
server/api/todo/dao/todo-dao.ts(2,26): error TS2307: Cannot find module
'bluebird'.
server/api/todo/dao/todo-dao.ts(3,20): error TS2307: Cannot find module
'lodash'.
server/api/todo/model/todo-model.ts(1,27): error TS2307: Cannot find module
'mongoose'.
server/api/todo/routes/todo-routes.ts(3,26): error TS2307: Cannot find
module 'express'.
server/commons/static/index.ts(3,26): error TS2307: Cannot find module
'express'.
server/commons/static/index.ts(4,21): error TS2307: Cannot find module 'fs'.
server/commons/static/index.ts(8,19): error TS2304: Cannot find name
'process'.
server/config/db.conf.ts(3,27): error TS2307: Cannot find module 'mongoose'.
server/config/db.conf.ts(4,15): error TS2304: Cannot find name 'require'.
server/config/db.conf.ts(8,20): error TS2304: Cannot find name 'process'.
server/config/db.conf.ts(8,61): error TS2304: Cannot find name 'process'.
server/config/routes.conf.ts(3,26): error TS2307: Cannot find module
'express'.
server/config/routes.conf.ts(4,25): error TS2307: Cannot find module
'morgan'.
server/config/routes.conf.ts(5,29): error TS2307: Cannot find module
'body-parser'.
server/config/routes.conf.ts(6,25): error TS2307: Cannot find module
'helmet'.
server/config/routes.conf.ts(10,21): error TS2304: Cannot find name
'process'.
server/config/routes.conf.ts(12,29): error TS2304: Cannot find name
'process'.
server/routes/index.ts(1,26): error TS2307: Cannot find module 'express'.
server/server.ts(1,1): error TS6053: File 'typings/index.d.ts' not found.
server/server.ts(5,22): error TS2304: Cannot find name 'process'.
server/server.ts(6,5): error TS2304: Cannot find name 'require'.
server/server.ts(8,12): error TS2304: Cannot find name 'process'.
server/server.ts(10,26): error TS2307: Cannot find module 'express'.
server/server.ts(11,21): error TS2307: Cannot find module 'os'.
server/server.ts(12,24): error TS2307: Cannot find module 'https'.
server/server.ts(13,21): error TS2307: Cannot find module 'fs'.
server/server.ts(25,24): error TS2304: Cannot find name '__dirname'.
server/server.ts(26,25): error TS2304: Cannot find name '__dirname'.
server/server.ts(32,35): error TS2304: Cannot find name 'process'.

**Comment by ericmdantas** [comment]
Looks like your first `typings install` didn't succeed.

Do the following:
- if you don't have typings install, run `npm i -g typings@lastest`
- run `typings install`
- run `tsc` again.

**Comment by adskiremote** [comment]
ok getting somewhere. Running tsc produces no errors.

Now when running npm run dev I get these:

error TS5023: Unknown compiler option 'moduleResolution'.

**Comment by ericmdantas** [comment]
Right. 

So, could you please:
- run `npm i --save-dev gulp-typescript@latest`
- run `npm i --save typescript@latest`
- run `npm run dev`

**Comment by adskiremote** [comment]
Perfect - running fine now.  Many thanks Eric appreciate your time and
effort to help me.

**Comment by ericmdantas** [comment]
No problem! Glad it helped. :smile:
