### ISSUE TITLE
One account multiple strategies

### ISSUE THREAD

**Issue by remicastaing** [ericmdantas/generator-ng-fullstack#17]
In https://github.com/DaftMonk/generator-angular-fullstack/issues/359, I shared a proposition for managing multiple authentication strategies for one account: having several `account` object (one for every auth strategy) for one `user` object.

The `account` object would keep the credential or the social id. Every `account` would be linked to the same `user` object after email confirmation. They would be no need for the dev to customize the model.

The `user` would keep the business information (name, email, age, address, etc...) needed for the app. All customization  would be kept in this model.

**Comment by ericmdantas** [comment]
Hey there, @remicastaing.

Looks like I've been working on a very similar thing back at work. We have these g+ and facebook accounts tied to a user. Seems like the same scenario.

I don't know if you've seen the todo app when you run ```yo ng-fullstack```, but I was thinking about making the todo app work with some sort of auth. You don't see the todo list until we know who you are.

Maybe we already could do such thing, like having facebook, twitter and suchs as a way to login - other than the classic form (email + password).

What do you think?

That way we could give a bunch of boilerplate and templates for the user.

**Comment by remicastaing** [comment]
I managed to install and run the generator yesterday night.
With G+ and FB, there is no problem to corallate two accounts: the provided email is already verified.
With a local or a Tw auth strategy, you have to confirm the email yourself first.

**Comment by ericmdantas** [comment]
I see.

What framework are going to use, or suggest? I remember [Passport](https://github.com/jaredhanson/passport) was pretty good - not sure if it's still being maintained.

And for the client, there's this [satellizer](https://github.com/sahat/satellizer) that I have heard before, but have never used.

**Comment by remicastaing** [comment]
With generator-angular-fullstack, there is passport on the server side and
no framework on the client side (lightweight custom code).

**Comment by ericmdantas** [comment]
Noted.

**Comment by ericmdantas** [comment]
Closing this, I don't think it belongs to the core.
