### ISSUE TITLE
Add option to work with Aurelia

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#175]
As suggested by @bernardbr in https://github.com/ericmdantas/generator-ng-fullstack/issues/161#issuecomment-227839310.

Reference: http://aurelia.io

**Comment by joelcoxokc** [comment]
Upvote

**Comment by ericmdantas** [comment]
Simple todo example: https://github.com/ericmdantas/aurelia-todo

**Comment by ericmdantas** [comment]
Implement all tests: unit and acceptance, whole generator and subgenerators.

**Comment by ericmdantas** [comment]
Unit tests done, missing acceptance tests - will do it later today.

**Comment by ericmdantas** [comment]
Make sure the path to the source code is set correctly by:

```js
System.config({
  paths: {
    '*': 'client/dev/*',
    // ...
  }
});
```

Reference: https://github.com/aurelia-guides/aurelia-jspm-issues/issues/3

**Comment by ericmdantas** [comment]
Done.
