### ISSUE TITLE
Update outdated deps and devDeps for the generated apps

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#185]
As pointed out by @Abdizriel (through #184), here are some of them:
- Express `4.13` -> `4.14`
- Helmet `0.7` -> `2.1`
- RxJS `5.x.beta-6` -> `beta9` (gotta check if it's compatible with ng2)
- del `1.1` -> `2.2`
- gulp-htmlmin `1.3` -> `2.0`
- gulp-imagemin `2.4` -> `3.0`
- istanbul `0.3` -> `0.4`
- karma `0.12` -> `1.0`
- karma-chrome-launcher `0.1` -> `1.0`
- karma-coverage `0.2` -> `1.0`
- karma-firefox-launcher `0.1` -> `1.0`
- karma-ie-launcher `0.1` -> `1.0`
- karma-jasmine `0.3` -> `1.0`
- karma-ng-html2js-preprocessor `0.1` -> `1.0`
- karma-opera-launcher `0.1` -> `1.0`
- karma-phantomjs-launcher `0.1` -> `1.0`
- karma-safari-launcher `0.1` -> `1.0`
- remove wiredep (not being used)

**Comment by Abdizriel** [comment]
@ericmdantas I have created some repositories like:
- ng-fullstack-ng1
- ng-fullstack-ng2
- ng-fullstack-node-express-standard
- ng-fullstack-node-express-babel
- ng-fullstack-node-express-typescript
- ng-fullstack-node-koa-standard
- ng-fullstack-node-koa-babel
- ng-fullstack-node-koa-typescript

And added Greenkeeper.io to watch for dependency updates. But I have to do some fixes with tests so it would show what can be merged without issues.

**Comment by ericmdantas** [comment]
Right, should I wait for the tests, then?

**Comment by ericmdantas** [comment]
Updated express all good for now.

**Comment by ericmdantas** [comment]
As suspected, `rxjs` can't be updated to `beta9`. The rest was updated just fine.

@Abdizriel do you need help updating those repos? I can send PRs.

**Comment by Abdizriel** [comment]
No, I will do that since I need to do some set up

**Comment by ericmdantas** [comment]
Alright. Let me know so we can do that and release 1.8.11.

**Comment by ericmdantas** [comment]
@Abdizriel can you update the deps against master, please?
