### ISSUE TITLE
Add option to work with message queue

### ISSUE THREAD

**Issue by Abdizriel** [ericmdantas/generator-ng-fullstack#186]
Add option to generator to work with message queue to go/node server with:
- Redis: http://redis.io/
- Kafka: http://kafka.apache.org/
- RabbitMQ: https://www.rabbitmq.com/

**Comment by ericmdantas** [comment]
Never thought about adding any of those, to be honest.

How'd that fit in the structure we have today without getting too specific? 
Say in the todo app, how would we make it "make sense"? And where else it fit for subgenerators?

**Comment by Abdizriel** [comment]
It would "make sense" in todo app if we consider thousands of people using application with authentication and their own boards of todo like work, home etc.

In that case every request is produced by user action like adding todo to board and consumed by API when there's free queue for consuming. We can add also message accept to be sure that job won't be lost if server went down and could be reproduced after server is on.

We won't need any other suubgenerators because everything of it would be done with endpoint subgenerator.

**Comment by ericmdantas** [comment]
Right, but then we'd have an option so the user can select if he wants to work with it or not. Because for smaller/pet projects, it'd be an overkill.

**Comment by Abdizriel** [comment]
That's why it would be optional because what you said about smaller projects.

**Comment by ericmdantas** [comment]
Too much for the boilerplate for now.
