### ISSUE TITLE
Add swagger to generate RESTful documentation

### ISSUE THREAD

**Issue by Abdizriel** [ericmdantas/generator-ng-fullstack#187]
Reference: http://swagger.io/

**Comment by ericmdantas** [comment]
Oh, @bernardbr is gonna like this one.

Is it doable for `1.9`? Considering the changes for both `go` and `node`.

**Comment by Abdizriel** [comment]
I think it is but I can only do that for node :)

**Comment by ericmdantas** [comment]
Cool, cool. I'll check some of the integrations: http://swagger.io/open-source-integrations/.

**Comment by ericmdantas** [comment]
Out of scope.
