### ISSUE TITLE
Fix issue with no starting node server

### ISSUE THREAD

**Issue by Abdizriel** [ericmdantas/generator-ng-fullstack#188]

**Comment by ericmdantas** [comment]
When does this happen?

**Comment by Abdizriel** [comment]
@ericmdantas every time I tried create just server node-express-babel
It doesn't matter if it is with separete/together tests and http2 security

**Comment by ericmdantas** [comment]
Against `master` or `1.9`?

**Comment by Abdizriel** [comment]
1.9

**Comment by ericmdantas** [comment]
Seems to be a problem with `node-typescript`. `node-standard` and `node-babel` are working just fine.

**Comment by ericmdantas** [comment]
On `node-typescript`, when trying to run `tsc` I get the following:

```
server/api/todo/dao/todo-dao.ts(27,29): error TS2304: Cannot find name 'todo'
```

**Comment by ericmdantas** [comment]
Should be fixed now, worked locally. Can you give it a try?

**Comment by Abdizriel** [comment]
Nope, still I can't use postman to try API.

I'll have a look into it now. When you generate fullstack project API is working.

**Comment by ericmdantas** [comment]
Are you targeting port `3333` or `3000`? The server runs on `3333`, `3000` is only available for live-reload.

**Comment by Abdizriel** [comment]
I tried everyone of them and none of them worked for me

**Comment by ericmdantas** [comment]
Closing as I can't reproduce it.
