### ISSUE TITLE
Have option to use either: ngResource or js-data model layer

### ISSUE THREAD

**Issue by Toub** [ericmdantas/generator-ng-fullstack#19]
As mentioned in #16 "Bower dependencies", we should introduce an abstraction layer such as js-data.

The basic:
* add bower dependency: js-data-angular
* load the module 'js-data' in client app.js
* configure the default behavior (by default use http://www.js-data.io/docs/dshttpadapter):

    DSProvider.defaults.basePath = '/api';
    DSProvider.defaults.idAttribute = '_id'; // for mongo-db

* define resources and relations-ships:

    DS.defineResource{
        name: 'users'
    });

* use it anywhere:

    DS.findAll('users').then(function (users) {
        $scope.users = users;
    });

The entities are cached by default so I love to use it in combination with web sockets to synchronize the cached collection with the server.

It could be a good idea to write a custom adapter to cover this case.

**Comment by ericmdantas** [comment]
Just as a reference for others, [here's a good video about it](https://www.youtube.com/watch?v=8wxnnJA9FKw).

**Comment by ericmdantas** [comment]
Just a question:

By using js-data, we'd still have the model for forms, right? [Like the todo.model.js](https://github.com/ericmdantas/generator-ng-fullstack/blob/master/app/templates/client/dev/js/todo/model/todo.model.js).

**Comment by jgodi** [comment]
Yes, you can see it here. http://www.js-data.io/v1.8.0/docs/js-data-angular

For me I can live without this js-data. I use Ember Data in a project and it over complicates things more so then some applications need. Would be nice for this to be an opt-in feature rather in a core feature.

**Comment by Toub** [comment]
You don't have to define all properties of your model, but you can: http://www.js-data.io/v1.8.0/docs/dsdefineresource

Here is how you can validate the model: http://www.js-data.io/v1.8.0/docs/schemata--validation

Maybe that jgodi is right, and that the user should be able to choose if using js-data, ngresource, restangular...

But the good of js-data is the abstraction layer so you can do powerfull things or change the way you store your data without impact on your services and controllers.

**Comment by ericmdantas** [comment]
For some reason the links are broken to me, I'll take a look when I get home.

But I agree with the opt thing.

For now, we could leave it between ```ngResource``` and ```js-data```.

**Comment by ericmdantas** [comment]
Droping from core.
