### ISSUE TITLE
Can't build at all... why?

### ISSUE THREAD

**Issue by JoelParke** [ericmdantas/generator-ng-fullstack#195]
I have a project built with angular-fullstack and I thought I would give ng-fullstack a try.
yo ng-fullstack runs to completion.
BUT gulp then gives:
```
19:10:04] Requiring external module babel-register
[19:10:04] Using gulpfile ~/workspace/Tracker3/gulpfile.babel.js
[19:10:04] Starting 'client.build_ts'...
/home/joel/workspace/Tracker3/node_modules/@angular/core/src/application_ref.d.ts(79,88): error TS2304: Cannot find name 'Promise'.
/home/joel/workspace/Tracker3/node_modules/@angular/core/src/application_ref.d.ts(137,42): error TS2304: Cannot find name 'Promise'.
/home/joel/workspace/Tracker3/node_modules/@angular/core/src/application_ref.d.ts(196,33): error TS2304: Cannot find name 'Promise'.
/
```
Clearly I am clueless, but the Trouble Shooting just seems to imply - don't bother yet with Angular 2 -- is that really true?
Thanks!

**Comment by JoelParke** [comment]
Attempting to go a little further, it stuck me that perhaps the installation didn't install all it need to.
So I did npm install angular2.  But that didn't help and so I did npm uninstall angular2 
So What gives? Any help would be appreciated.

**Comment by ericmdantas** [comment]
Hello, @JoelParke.

Did you manage to solve it? The problem the troubleshooting talks about is the testing with Angular2, compiling using `tsc` should work fine.

**Comment by JoelParke** [comment]
Thanks Eric,

I shifted directions and moved over to generator-react-fullstack and will
probably come back as I more fully decide on the direction for my rewrite
of my angular1 stable app.

Thanks,
Joel

**Comment by ericmdantas** [comment]
Alright, let me know if you need anything.
