### ISSUE TITLE
Store 'appName' in .yo-rc.json

### ISSUE THREAD

**Issue by jgodi** [ericmdantas/generator-ng-fullstack#20]
While I am going through each client side file and making them conform to the style guide, I have noticed that the sub generators do not know about the application name. Therefore, they are not able to automatically have the correct module name.

I propose we utilize the [Yeoman Config](http://yeoman.io/authoring/storage.html) to save that variable (and any other required variables) inside the `.yo-rc.json` file.

We then can use this in all our sub generators. This will require the user to use the base generator first before using the sub generators, if we wanted to fix this we could put in another prompt in the sub generators that would ask the user for the `moduleName` IF we cannot find the `appName` inside the `.yo-rc.json`

Thoughts?

**Comment by ericmdantas** [comment]
Definetely.

I will have to use it for the ```go``` integration as well, for when the user chooses to create an endpoint, I'll have to know if it's for ```io.js``` or ```go```.

I haven't create the api for the writing there, but make sure we separate this generator (generator-ng-fullstack) from the others. Like:

```json
{
    "generator-ng-fullstack":
    {
        "appName": "GoesHere",
        "server": "go"
    }
}
```

Maybe we could even fill this file with the default stuff and let the user change it by hand?

**Comment by ericmdantas** [comment]
Already doing this. Gonna push 1.3 soon.

If there's anything, let me know.
