### ISSUE TITLE
Choosing Babel will generate typescript client

### ISSUE THREAD

**Issue by joelcoxokc** [ericmdantas/generator-ng-fullstack#200]

**Comment by ericmdantas** [comment]
Hey there, @joelcoxokc.

The babel option is only meant for the server. Once you choose ng2, you'll get the typescript version - that's by design.

**Comment by ericmdantas** [comment]
When #175 (branch v1.9) lands, we'll probably have more transpilers for the client, because of Vue/Aurelia in client.

**Comment by ericmdantas** [comment]
The initial Aurelia version (to be released in 1.9) will have babel as the transpiler. Typescript should follow in the next version - DB changes is probably going to be 1.11, instead of 1.10.
