### ISSUE TITLE
golang GetById some type bug 1.9

### ISSUE THREAD

**Issue by tedpark** [ericmdantas/generator-ng-fullstack#204]
I found some minor type bug.

ex)
func GetById(string id) (todo.Todo, error) {
...............
}

=>

func GetById(id string) (todo.Todo, error) {
}

is correct.

ex)
GetById(string id) => GetById(id string)

Thanks.

p.s. I'm newbie because I can't change bug fix. ;-)

<img width="658" alt="screen shot 2016-08-04 at 2 04 00 pm" src="https://cloud.githubusercontent.com/assets/6670962/17390927/65f4d7b2-5a4c-11e6-8c3d-f38a78de77b1.png">

**Comment by ericmdantas** [comment]
Hey there, @tedpark!

Thanks for the heads up. I'll release a patch in a sec.

**Comment by ericmdantas** [comment]
Fixed :+1:

**Comment by tedpark** [comment]
Good job!! ;-)
