### ISSUE TITLE
golang mgo GetById some bug 1.9

### ISSUE THREAD

**Issue by tedpark** [ericmdantas/generator-ng-fullstack#205]
I found some minor mgo bug.

ex)
func GetById(id string) (todo.Todo, error) {
    ....
    err = c.Find(bson.M{}).FindId(id).One(&t)   =>   (not working)
    ....
}

func GetById(id string) (todo.Todo, error) {
    ....
    err = c.Find(bson.M{"_id" : bson.ObjectIdHex(id)}).One(&t)   =>   (working)
    ....
}

is correct. (I think.)

---add please.---
ex)
e.GET("/api/todos/:id", todocontroller.GetById)

Thanks ;-)
p.s. I'm newbie because I can't change bug fix. ;-)

**Comment by ericmdantas** [comment]
On it.

**Comment by ericmdantas** [comment]
Fixed.

Thanks once again :smile:

**Comment by tedpark** [comment]
Thanks! Good job! ;-)

**Comment by tedpark** [comment]
@ericmdantas

app/templates/server_go/gin/api/todo/route/todoroute.go

 func Init(r *echo.Echo) {
  	r.GET("/api/todos", todocontroller.GetAll)
 +	r.GET("/api/todos/:id", todocontroller.GetAll)    ->  (...todocontroller.GetById)
  	r.POST("/api/todos", todocontroller.NewTodo)
  	r.DELETE("/api/todos/:id", todocontroller.RemoveTodo)
  }

Thanks ;-)

**Comment by ericmdantas** [comment]
Ooops! There, fixed :laughing:

**Comment by ericmdantas** [comment]
There are still changes to be done in the gin server, by the way. 

I'll get back to it when the `less/sass` issue is done.
