### ISSUE TITLE
Compile error from @angular/core/testing

### ISSUE THREAD

**Issue by tejasbehra** [ericmdantas/generator-ng-fullstack#207]
tests/client/todo/components/todo-cmp_test.ts(4,3): error TS2305: Module node_modules/@angular/core/testing"' has no exported member 'it'.
tests/client/todo/components/todo-cmp_test.ts(5,3): error TS2305: Module node_modules/@angular/core/testing"' has no exported member 'expect'.
tests/client/todo/components/todo-cmp_test.ts(6,3): error TS2305: Module @angular/core/testing"' has no exported member 'describe'.
tests/client/todo/components/todo-cmp_test.ts(10,3): error TS2305: Module
node_modules/@angular/core/testing"' has no exported member 'beforeEachProviders'.

node - v6.3.0
tsc - Version 2.1.0-dev.20160810
npm - 3.10.3
Ubuntu 14.04.4 LTS

**Comment by ericmdantas** [comment]
Hey there, @tejasbehra. That's because of the latest release candidate for ng2. We're tracking it here: #206.

I'll leave this one open so people can see what's going on.

**Comment by ericmdantas** [comment]
1.8.18 released with the typings fixed. 

`RC5` is not completely implemented, though.

**Comment by ericmdantas** [comment]
1.8.19 released with the `NgModules` (RC5).
