### ISSUE TITLE
tsc fails on excluding node_modules if we have typings in exclude

### ISSUE THREAD

**Issue by tejasbehra** [ericmdantas/generator-ng-fullstack#208]
node - v6.3.0
tsc - Version 2.1.0-dev.20160810
npm - 3.10.3
Ubuntu 14.04.4 LTS

1) When i include typings in exclude - 
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es5",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noImplicitAny": false
    },
    "exclude": [
      "typings",
      "node_modules"
    ],
    "filesGlob": [
      "**/*.ts",
      "typings/main",
      "typings/index.d.ts"
    ]
}

Result in following errors -
node_modules/@angular/http/src/headers.d.ts(45,59): error TS2304: Cannot find name 'Map'.
node_modules/@angular/http/src/url_search_params.d.ts(46,16): error TS2304: Cannot find name 'Map'.
node_modules/@angular/platform-browser-dynamic/index.d.ts(98,104): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/index.d.ts(104,99): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/index.d.ts(118,113): error TS2304: Cannot find name 'Promise'.
node_modules/@angular/platform-browser-dynamic/src/facade/lang.d.ts(11,17): error TS2304: Cannot find name 'Map'.
node_modules/@angular/platform-browser-dynamic/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Set'.
node_modules/@angular/platform-browser-dynamic/src/facade/lang.d.ts(67,59): error TS2304: Cannot find name 'Map'.
node_modules/rxjs/Observable.d.ts(10,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,60): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(66,70): error TS2304: Cannot find name 'Promise'.
server/app/config_app/controller/config_app_ctrl.ts(2,26): error TS2307: Cannot find module 'express'.
server/app/config_app/model/config_app_mdl.ts(2,25): error TS2307: Cannot find module 'xml-to-json-promise'.
server/app/config_app/model/config_app_mdl.ts(3,26): error TS2307: Cannot find module 'bluebird'.
server/app/config_app/route/config_app_rt.ts(3,26): error TS2307: Cannot find module 'express'.
server/config/routes.conf.ts(3,26): error TS2307: Cannot find module 'express'.
server/config/routes.conf.ts(4,25): error TS2307: Cannot find module 'morgan'.
server/config/routes.conf.ts(5,29): error TS2307: Cannot find module 'body-parser'.
server/config/routes.conf.ts(6,25): error TS2307: Cannot find module 'helmet'.
server/config/routes.conf.ts(10,21): error TS2304: Cannot find name 'process'.
server/config/routes.conf.ts(12,29): error TS2304: Cannot find name 'process'.
server/dnlogging/dn_logger.ts(1,25): error TS2307: Cannot find module 'bunyan'.
server/dnlogging/dn_logger.ts(2,25): error TS2307: Cannot find module 'extend'.
server/dnlogging/dn_logger.ts(3,29): error TS2307: Cannot find module 'object-path'.
server/dnlogging/dn_logger.ts(4,30): error TS2307: Cannot find module 'bunyan-kafka'.
server/dnlogging/dn_logger.ts(5,33): error TS2307: Cannot find module 'bunyan-logstash'.
server/dnlogging/dn_logger.ts(6,23): error TS2307: Cannot find module 'path'.

2) on removing typings from exclude code compiles -
{
    "compilerOptions": {
        "module": "commonjs",
        "moduleResolution": "node",
        "target": "es5",
        "sourceMap": true,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "noImplicitAny": false
    },
    "exclude": [
      "node_modules"
    ],
    "filesGlob": [
      "**/*.ts",
      "typings/main",
      "typings/index.d.ts"
    ]
}

**Comment by ericmdantas** [comment]
Did you run `typings install`?

**Comment by tejasbehra** [comment]
My mistake, was not not using  reference to typings index correctly, thanks
