### ISSUE TITLE
Implement Style Guide

### ISSUE THREAD

**Issue by jgodi** [ericmdantas/generator-ng-fullstack#21]
Implement the [John Papa's Style Guide](https://github.com/johnpapa/angular-styleguide/blob/master/README.md) for client side code.

**Comment by jgodi** [comment]
Work can be seen in my [fork](https://github.com/jgodi/generator-ng-fullstack). Hopefully be finished by the weekend :)

**Comment by ericmdantas** [comment]
Can't wait!

Let me kbnow if you need anything :smile:

**Comment by ericmdantas** [comment]
Closing this. PR still got some stuff to fix, like Travis build and so on. 

Just waiting for the changes so I can merge.
