### ISSUE TITLE
tsc does not throw error when compile server files if node_modules not present 

### ISSUE THREAD

**Issue by tejasbehra** [ericmdantas/generator-ng-fullstack#210]
I am not sure whether this make sense, but when i try to compile the client directory **moving out the node_modules from cwd to some other directory** (not in project hierarchy, make sure its not visible) it results in following error -
client/dev/app.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
client/dev/app.module.ts(2,28): error TS2307: Cannot find module '@angular/http'.
client/dev/app.module.ts(3,68): error TS2307: Cannot find module '@angular/forms'.
client/dev/app.module.ts(4,32): error TS2307: Cannot find module '@angular/platform-browser'.
client/dev/index.ts(1,38): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.
client/dev/todo/components/todo-cmp.ts(5,8): error TS2307: Cannot find module '@angular/core'.
client/dev/todo/components/todo-cmp.ts(12,8): error TS2307: Cannot find module '@angular/forms'.
client/dev/todo/services/todo-service.ts(4,8): error TS2307: Cannot find module '@angular/core'.
client/dev/todo/services/todo-service.ts(8,8): error TS2307: Cannot find module 'rxjs/Observable'.
client/dev/todo/services/todo-service.ts(13,8): error TS2307: Cannot find module '@angular/http'.
tests/client/todo/components/todo-cmp_test.ts(8,8): error TS2307: Cannot find module '@angular/core/testing'.
tests/client/todo/components/todo-cmp_test.ts(12,8): error TS2307: Cannot find module 'rxjs/Observable'.

But when i compile server files it does not throw any such error, what exactly be the cause ?
I have typing install correctly and using node-v6, tsc-2.1

**Comment by ericmdantas** [comment]
That's because Angular and RxJs have their typings inside `node_modules`, while `express`, `mongoose` and others, have their typings inside the `typings` folder.

**Comment by tejasbehra** [comment]
Hi ericmdantas, Could there be a way to have similar mechanism to catch this error on server side ?

**Comment by ericmdantas** [comment]
I don't think we can do much about it, that'd be up to those packages and its maintainers. But since they're written in pure javascript, the community is the one taking care of all the typings. 

In Angular's case, the core team's build generates the typings, so the community doesn't have to.
