### ISSUE TITLE
How to update generator-ng-fullstack files ?

### ISSUE THREAD

**Issue by codestorycooked** [ericmdantas/generator-ng-fullstack#212]
I see this generator was updated 2 days ago on yo. How do I update my existing project created using this generator so to be synced up with latest and good practice or any other issue fixed in a generator?

Thanks is advance
Kunal D.

**Comment by ericmdantas** [comment]
Hey there.

It should be just the typical npm install: `npm i -g generator-ng-fullstack@latest`.

As for the changes, the only thing that changed was the bump in ng2 version - from rc4 to rc5 - which introduced the `NgModule` breaking change.
