### ISSUE TITLE
Fix Heroku build for Angular2

### ISSUE THREAD

**Issue by jorys** [ericmdantas/generator-ng-fullstack#213]
Hello,

When I do a `git push heroku master`, it never builds due to typings and tsc missing.
I had to modify package.json like this :
-  Add typings install : `"preinstall": "npm i typings -g && typings install",`
-  Remove postinstall with tsc call

Can you tell me if I have done right or tell me what can I do?
Thanks for your help.

**Comment by ericmdantas** [comment]
Hey there, @jorys.

Why would you have to remove the `postinstall: tsc` script? 

As for the installation of typings, that's really needed, but I don't know if I'd update the global version in the user's machine, it could break other projects. Have you tried installing `typings` locally, assigning it to a script, say `install-types: typings install` and then running `npm run install-types`?

**Comment by ericmdantas** [comment]
Also, could you please show me the error message you got so I can put in the `troubleshooting` part of the wiki?

**Comment by jorys** [comment]
Hello,

Here are the logs:
   -   When I use default package.json: [typings.txt](https://github.com/ericmdantas/generator-ng-fullstack/files/419994/typings.txt)
   -   When I put `"preinstall": "npm i typings -g && typings install"`: [tsc.txt](https://github.com/ericmdantas/generator-ng-fullstack/files/419993/tsc.txt)
If I do not put the installation of typings during preinstall, it is not found by heroku.

Another detail, in the wiki, in the heroku deployment, you should specify that MONGOLAB_URI must be modified in /server/config/db.conf.ts file.

**Comment by ericmdantas** [comment]
Right, can you try installing both `typescript` and `typings` locally instead of globally and try to deploy to Heroku?

```shell
$ npm i --save-dev typings typescript
```

And then remove your `npm i typings -g`. NPM should pick the local deps.

That should fix the errors - if so - I can release a a patch in a minute.

**Comment by ericmdantas** [comment]
Also, move the `typings install` from `preinstall` to `postinstall`, please.
