### ISSUE TITLE
Unit test error: [web-server]: 404: /base/node_modules/@angular/http

### ISSUE THREAD

**Issue by cilginbok** [ericmdantas/generator-ng-fullstack#214]
Hello,
After a fresh build, when i write `npm run build-dist` , i had this error:

![image](https://cloud.githubusercontent.com/assets/18344355/17663655/c82e9294-62f6-11e6-94ae-85b83db8ad01.png)

What am I doing wrong?

**Comment by ericmdantas** [comment]
Hello, @cilginbok.

You've ran into https://github.com/ericmdantas/generator-ng-fullstack/issues/101, if you want to just build your app without the tests, just go to `tasks/client/build.js` and comment the unit test line.
