### ISSUE TITLE
js and css files are served with text/html MIME type  | npm run dev

### ISSUE THREAD

**Issue by Karel-Kroeze** [ericmdantas/generator-ng-fullstack#216]
After a fresh yo ng-fullstack with the following settings;

```
{
  "generator-ng-fullstack": {
    "username": "Karel-Kroeze",
    "appName": "test",
    "stack": "fullstack",
    "server": "node",
    "client": "ng1",
    "transpilerServer": "node",
    "secure": false,
    "differentStaticServer": false
  }
```

and running the documented `npm run dev`, browser refuses to load the ToDo app, since MIME types don't match.

This is on a Ubuntu 14.04 box, it looks similar to #151, but that refers to deploying to heroku. I have yet to try a deployed dist build, so can't comment on that.

**Comment by ericmdantas** [comment]
Hey there, @Karel-Kroeze.

Just tried to reproduce it, but couldn't do it, but I'm on windows, so that could indicate something.

Couple questions:
- Does accessing `http://localhost:3333/api/todos` return an empty array?
- Could you please change the content of `server/commons/static/index.js` to:

```js
"use strict";

const fs = require('fs');
const path = require('path');

module.exports = class StaticDispatcher {
    static sendIndex(req, res) {
      var _root = process.cwd();

      res.type('.html');

      fs.createReadStream(path.join(_root + '/client/dev/index.html'))
        .pipe(res);
    }
}

```

And then run `npm run dev` again.

Let me know how it goes.

**Comment by ericmdantas** [comment]
If that doesn't work, try using `path.join` in `server/config/routes.config.js` too:

```js
// Before

       application.use(express.static(_root + _nodeModules));
       application.use(express.static(_root + _clientFiles));
```

```js
// After

       application.use(express.static(path.join(_root, _nodeModules)));
       application.use(express.static(path.join(_root + _clientFiles)));
```

**Comment by ericmdantas** [comment]
Closing as there was no response.
