### ISSUE TITLE
Error @ npm install: postintall: 'tsc'

### ISSUE THREAD

**Issue by mehdimj** [ericmdantas/generator-ng-fullstack#217]
![image](https://cloud.githubusercontent.com/assets/5819192/18233159/7b82a374-72ad-11e6-86fd-89f699341fd1.png)

This error occurs during npm install. Any clue to fix that ?

Thanks

**Comment by ericmdantas** [comment]
Hello, @mehdimj.

Is there any typing errors above this one? Also, the stack you're using involves `ng2`?

**Comment by mehdimj** [comment]
Hey @ericmdantas,

Nope there are no errors above that one but few warnings. I  chose ng2, node, typescript :)
PS: I tried the same stack on another machine like 3 weeks ago and it's running fine.

Thanks

**Comment by mehdimj** [comment]
Here is a screenshot of what's above:

![image](https://cloud.githubusercontent.com/assets/5819192/18233848/3a142dea-72c1-11e6-8a09-d8fd335efdab.png)

Thanks

**Comment by ericmdantas** [comment]
Right, it's because of the update from ng2 `rc5` to `rc6`, they broke some of the typings and I'll have to update it in a patch.

**Comment by mehdimj** [comment]
Sounds good ! Is there any way to receive a notification when the update is done or i'll just have to install the generator from time to time and give it a try ?

**Comment by ericmdantas** [comment]
If you're watching the repo, you'll have a notification, if not, I'll target this issue in the commit and I can ping you.

But, keep in mind that choosing ng2 you'll end up having these problems from time to time, because of all the changes on their side.

**Comment by mehdimj** [comment]
Perfect, thanks a lot !

**Comment by ericmdantas** [comment]
There are a bunch of breaking changes, but some seem to be missing: https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc6-2016-08-31

Here's a example of a new `system.config.js`: https://github.com/angular/quickstart/blob/3b7452cc444c49c139ea39523ced0468c2362c16/systemjs.config.js#L17-L34

Test changes: https://github.com/juliemr/ng2-test-seed

--

I'm probably doing it tomorrow.

**Comment by ericmdantas** [comment]
`1.8.21` released with ng2 updated to `rc6`.

**Comment by tiagobsbraga** [comment]
In my case was install typing as global

`npm install typings -g`
