### ISSUE TITLE
npm run watch Error

### ISSUE THREAD

**Issue by panasevich** [ericmdantas/generator-ng-fullstack#219]
I've got installed fullstack(angular2+tsc) and I've got an error error after starting npm run watch:

Requiring external module babel-register
[11:07:51] Using gulpfile D:\eventSite\gulpfile.babel.js
[11:07:51] Starting 'client.build_ts'...
client\dev\index.ts(3,9): error TS2305: Module '"D:/eventSite/node_modules/@angular/http/index"' has no exported member 'HTTP_PROVIDERS'.
client\dev\todo\components\todo-cmp.ts(28,3): error TS2345: Argument of type '{ selector: string; templateUrl: string; styleUrls: string[]; directives: any[][]; providers: typ...' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.
D:/eventSite/node_modules/@angular/forms/src/directives.d.ts(44,39): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
D:/eventSite/node_modules/@angular/forms/src/directives.d.ts(48,48): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
D:/eventSite/node_modules/@angular/forms/src/form_providers.d.ts(13,38): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
tests\client\todo\components\todo-cmp_test.ts(4,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'it'.
tests\client\todo\components\todo-cmp_test.ts(5,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'expect'.
tests\client\todo\components\todo-cmp_test.ts(6,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'describe'.
tests\client\todo\components\todo-cmp_test.ts(9,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'TestComponentBuilder'.
tests\client\todo\components\todo-cmp_test.ts(10,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'beforeEachProviders'.
tests\client\todo\components\todo-cmp_test.ts(14,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/index"' has no exported member 'provide'.
tests\client\todo\services\todo-service_test.ts(4,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'it'.
tests\client\todo\services\todo-service_test.ts(5,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'expect'.
tests\client\todo\services\todo-service_test.ts(6,3): error TS2305: Module '"D:/eventSite/node_modules/@angular/core/testing/index"' has no exported member 'describe'.
[11:07:54] TypeScript: 14 semantic errors
[11:07:54] TypeScript: emit succeeded (with errors)
[11:07:54] Finished 'client.build_ts' after 2.85 s
[11:07:54] Starting 'client.watch'...
[11:07:54] Finished 'client.watch' after 93 ms
[11:07:54] Starting 'default'...
[11:07:54] Finished 'default' after 11 μs
[BS] Proxying: https://localhost:3333
[BS] Access URLs:

How should I fix it?

**Comment by ericmdantas** [comment]
Hello, @panasevich.

Either the typings were not installed[0], or you have an older version of the generator[1].

To solve [0], run `typings install` and to solve [1], run `npm i -g generator-ng-fullstack@latest`.

Let me know how it goes.

**Comment by panasevich** [comment]
Hello, @ericmdantas 

npm i -g generator-ng-fullstack@latest helped me.

Thanks a lot!

**Comment by ericmdantas** [comment]
Awesome!
