### ISSUE TITLE
Generating the project doesn't complete

### ISSUE THREAD

**Issue by jpaaso** [ericmdantas/generator-ng-fullstack#221]
Hi,

I'm trying to generate the project but it gets stuck at:

```
> myproject@0.0.1 postinstall /Users/jpaaso/dev/yo/myproject
> tsc

myproject@0.0.1 /Users/jpaaso/dev/yo/myproject
...
└── zone.js@0.6.25 
```

Is there a way to get a more verbose output? Thanks.

**Comment by ericmdantas** [comment]
Hello, @jpaaso.

Can you share what's the content of your `.yo-rc.json`, please?

**Comment by ericmdantas** [comment]
Closing due to no response.

Feel free to reopen, if needed.

**Comment by jpaaso** [comment]
Hi,

I've tried different combinations but here's the last `.yo-tc.json`:
```
{
  "generator-ng-fullstack": {
    "username": "jpaaso",
    "appName": "simplia",
    "stack": "fullstack",
    "server": "go",
    "client": "ng2",
    "secure": false,
    "differentStaticServer": false
  }
}
```

**Comment by ericmdantas** [comment]
Thanks, I'll try to reproduce it.

**Comment by ericmdantas** [comment]
Alright, couldn't do it. A few questions:
- Do you have `tsc` and `typings` installed globally? If so, what's their versions?
- Can you run `npm i` in your project? Does it work as expected?
- What happens when you exclude your `node_modules` folder and run `npm i` again?

**Comment by jpaaso** [comment]
Installing `tsc`and `typings` solved the problem. Didn't realise they are required.

Thanks a lot!

**Comment by ericmdantas** [comment]
Awesome!
