### ISSUE TITLE
go get error

### ISSUE THREAD

**Issue by 6farer** [ericmdantas/generator-ng-fullstack#222]
When I run `go get` I get the following error:
```
# cd .; git clone https://github.com/{user}/{repo}
/Users/eric/go/src/github.com/{user}/{repo}
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

I haven't used go before so please bear with me. I never specified the repo or my user and intend on putting this app on a private GitHub repo, so I changed the user from my GitHub username to the GitHub organization, but the same error happens displaying the user instead of the organization.

**Comment by ericmdantas** [comment]
Hello, @6farer.

You'll have to setup your workspace to work with go, see how: https://golang.org/doc/code.html

And then, when you run `yo ng-fullstack`, you'll have to be insice `$GOPATH/src/github.com/{user}/{project}`.
