### ISSUE TITLE
[subgenerator/node_endpoint] - many typos error in generated code

### ISSUE THREAD

**Issue by jariwbh** [ericmdantas/generator-ng-fullstack#223]
Hi Guys,

I see many typos error in generated endpoints. i spent time to sort out why my webservices not returning data as ToDo endpoint do.

Regards,

**Comment by ericmdantas** [comment]
Hello, @jariwbh. Thanks for letting us know.

What the stack did you choose? Can you share the content of your `.yo-rc.json`, please?

Also, PRs are welcome, if you've got time, feel free to send a fix :wink:

**Comment by jariwbh** [comment]
Stack I choose was:

nodejs babel typescript ng2

Regards,
Bharat Jariwala
CEO/Founder , Krtya Software
Mobile - 8758363925

**Comment by jariwbh** [comment]
Sure, Let me know how to become part of community

**Comment by ericmdantas** [comment]
You could try to solve this issue against master 😄

**Comment by jariwbh** [comment]
I fixed issue. however, i could not commit changes 

its saying "remote: Permission to ericmdantas/generator-ng-fullstack.git denied to jariwbh."

**Comment by ericmdantas** [comment]
Commit to your repo first and then do a pull request.

See if this helps: https://www.thinkful.com/learn/github-pull-request-tutorial/#Opening-Your-Pull-Request

**Comment by jariwbh** [comment]
Submitted push request

**Comment by ericmdantas** [comment]
`v1.8.33` released with the fix.
