### ISSUE TITLE
[es6-shim]: error TS2300: Duplicate identifier 'PropertyKey'.

### ISSUE THREAD

**Issue by booradleys** [ericmdantas/generator-ng-fullstack#225]
Hi there, here is my error.
I had to remove to following line from typings/index.d.ts:
/// \<reference path="globals/es6-shim/index.d.ts" /\>
to let it work.
Is it the correct way ?

C:\Applications\Node\NgFullStack>npm run dev

> NgFullStack@0.0.1 dev C:\Applications\Node\NgFullStack
> tsc && concurrently "npm start" "gulp"

typings/globals/core-js/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'.
typings/globals/es6-shim/index.d.ts(3,14): error TS2300: Duplicate identifier 'PropertyKey'.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.7.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! NgFullStack@0.0.1 dev: `tsc && concurrently "npm start" "gulp"`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the NgFullStack@0.0.1 dev script 'tsc && concurrently "npm start" "gulp"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the NgFullStack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "npm start" "gulp"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs NgFullStack
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls NgFullStack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Applications\Node\NgFullStack\npm-debug.log

**Comment by ericmdantas** [comment]
Hello, @booradleys.

Did you install `core-js` by your own? Because it'll probably conflict with `es6-shim`.

**Comment by booradleys** [comment]
Hi @ericmdantas, No, i did not install by my own, but yes i think core-js and es6-shim conflict each others.
I don't know why.

**Comment by ericmdantas** [comment]
Right.

What's the content of your `.yo-rc.json`?

**Comment by booradleys** [comment]
Here it is : 

{
  "generator-ng-fullstack": {
    "username": "booradleys",
    "appName": "NgFullStack",
    "stack": "fullstack",
    "server": "node",
    "client": "ng2",
    "transpilerServer": "typescript",
    "secure": false,
    "differentStaticServer": false
  }
}

**Comment by ericmdantas** [comment]
Right, thanks!

I'll try to reproduce it.

**Comment by ericmdantas** [comment]
Hmm, couldn't reproduce it. There's no `core-js` entry in typings.json or folder in `typings/globals`.

Did you install anything other than the boilerplate app?

**Comment by booradleys** [comment]
Ah, it's weird!
I installed first angular2 and followed tutorial "Tour of heroes".

**Comment by ericmdantas** [comment]
Yeah, they do ask you to install core-js and it's typings, see https://angular.io/docs/ts/latest/quickstart.html > `Create configuration files` > `typings.json`.

Just stick with either `core-js` or `es6-shim` and you're fine :smile:

**Comment by booradleys** [comment]
Thank you @ericmdantas !!

**Comment by ericmdantas** [comment]
You're welcome :+1:
