### ISSUE TITLE
1.8.3.7 typescript and module compression

### ISSUE THREAD

**Issue by pharindoko** [ericmdantas/generator-ng-fullstack#231]
Hey,

tried to run the fullstack for version and received an error in the postinstall.
So when it tried to compile the typescript, I receive the error:
Cannot find module "compression".

Reason is that the typings file for compression is missing.
An install of this fixed the problem.

**Comment by ericmdantas** [comment]
Hello, @pharindoko.

How did you install `compression` through `typings`? What's the command? I can't find it in the registry.

**Comment by ericmdantas** [comment]
Nevermind, the command is: `typings install dt~compression --save --global`

**Comment by ericmdantas** [comment]
`1.8.38` released with the fix.

**Comment by pharindoko** [comment]
Sorry for rhe late response...correct - this is the command I meant :)

**Comment by ericmdantas** [comment]
No problem, thanks for the heads up :+1:
