### ISSUE TITLE
OpenShift deploy

### ISSUE THREAD

**Issue by uiktiomasfeliz** [ericmdantas/generator-ng-fullstack#232]
Support for OpenShift deploy.

**Comment by ericmdantas** [comment]
Hello, @uiktiomasfeliz.

What's needed to do such?

**Comment by uiktiomasfeliz** [comment]
i've tried create a OpenShift app and got this log:

---> Installing application source ...
---> Building your Node application from source
npm info it worked if it ends with ok
npm info using npm@2.15.1
npm info using node@v4.4.2
npm info preinstall GymCampaign@0.0.1

> GymCampaign@0.0.1 preinstall /opt/app-root/src
> typings install

sh: typings: command not found

npm info GymCampaign@0.0.1 Failed to exec preinstall script
npm ERR! Linux 3.10.0-514.el7.x86_64
npm ERR! argv "/opt/rh/rh-nodejs4/root/usr/bin/node" "/opt/rh/rh-nodejs4/root/usr/bin/npm" "install" "-d"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.1
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! GymCampaign@0.0.1 preinstall: `typings install`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the GymCampaign@0.0.1 preinstall script 'typings install'.
npm ERR! This is most likely a problem with the GymCampaign package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs GymCampaign
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls GymCampaign
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app-root/src/npm-debug.log

error: build error: non-zero (13) exit code from registry.ops.openshift.com/rhscl/nodejs-4-rhel7@sha256:6fa639325fe65eaf42931abc839c9626d94e2dde3110b4e7f80706f0fa2d169b


it can be done like this [article](https://developers.openshift.com/languages/nodejs/example-meanstack.html)?

**Comment by ericmdantas** [comment]
Looks like it's the same problem of #213.

The openshift deploy should work effortless once that's fixed.

**Comment by uiktiomasfeliz** [comment]
@ericmdantas i tried that solution, no result for me or i don`t know how to implement it :(
I will be grateful if you can upload an fullstack version with angular 2 client and nodejs server(todo example).

**Comment by ericmdantas** [comment]
I'll close as a duplicate and keep in mind to have an example to make it work.
