### ISSUE TITLE
js and css files are served with text/html MIME type | npm run dev

### ISSUE THREAD

**Issue by high-malloy** [ericmdantas/generator-ng-fullstack#233]
Have the same problem as here: 

https://github.com/ericmdantas/generator-ng-fullstack/issues/216

After a fresh yo ng-fullstack with the following settings;

{
  "generator-ng-fullstack": {
    "username": "XXXX",
    "appName": "test",
    "stack": "fullstack",
    "server": "node",
    "client": "ng2",
    "transpilerServer": "node",
    "secure": false,
    "differentStaticServer": false
  }
and running the documented npm run dev, browser refuses to load the ToDo app, since MIME types don't match.

This is on a Windows. I try to load moment.js, for example

Here a snippet of index.html: 

<!doctype html>
<html>
  <head>
    <base href="/" >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
    <link rel="shortcut icon" type="image/ico" href="favicon.png" />
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet" type="text/css">

    <script src="node_modules/moment/moment.js"></script>

    <title>ng2do</title>
............

**Comment by ericmdantas** [comment]
Hello, @high-malloy. It doesn't happen in my Windows machine.

Do you have any repo I can take a look/clone?

**Comment by ericmdantas** [comment]
Dup of #216
