### ISSUE TITLE
Integrating AngularFire2 and other dependencies

### ISSUE THREAD

**Issue by inicio** [ericmdantas/generator-ng-fullstack#234]
Is there any documentation available that shows how to add a dependency, particularly AngularFire2?  

I've followed the instructions for the library without success. It seems like this generator has its own project structure, which I'm not quite sure how to navigate.  

Thanks.

**Comment by ericmdantas** [comment]
Hello, @inicio.

It should be as simple as `npm install firebase angularfire2 --save` and adding the path to the lib in the `client/dev/config.js`.

**Comment by inicio** [comment]
Were it so simple! Just did a fresh install, and the error I'm getting in Chrome's console is thus:

`Unhandled Promise rejection: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <`

And this is referring to this line in app-module.ts

`import { AngularFireModule } from 'angularfire2';` 

Should I assume it's something related to the Angular library, and not this project?

**Comment by ericmdantas** [comment]
It's more like an issue with your `config.js`.

Can I see what's its content?

**Comment by inicio** [comment]
Certainly. 

`System.config({
  defaultJSExtensions: true,
  paths: {
    // paths serve as alias
    'npm:': './'
  },
  // map tells the System loader where to look for things
  map: {
    // our app is within the app folder
    app: 'app',

    // angular bundles
    '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
    '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
    '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
    '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
    '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
    '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
    '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
    '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

    // other libraries
    'rxjs':                       'npm:rxjs',
    'firebase':'npm:firebase',
    'angularfire2':'npm:angularfire2'
  }
});`

**Comment by ericmdantas** [comment]
You should add the path to the `angularfire2` dist folder in the `map` section of the `config.js`.

**Comment by inicio** [comment]
Thanks for you help, but something's still buggered. I'll try the library with another generator and see if it's not the problem.

**Comment by ericmdantas** [comment]
:+1:

**Comment by kieranfraser** [comment]
@ericmdantas  what should the config.js look like? I seem to be getting the same error as inicio and I'm unsure what you mean by "path to the angularfire2 dist folder" (currently my config.js is identical to inicio's)

**Comment by kieranfraser** [comment]
Got it - final config.js:

`System.config({
	defaultJSExtensions: true,
  paths: {
    // paths serve as alias
    'npm:': './'
  },
  // map tells the System loader where to look for things
  map: {
    // our app is within the app folder
    app: 'app',

    // angular bundles
    '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
    '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
    '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
    '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
    '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
    '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
    '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
    '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',

    // other libraries
    'rxjs':                       'npm:rxjs',
    'angularfire2':               'npm:angularfire2/bundles/angularfire2.umd.js',
    'firebase':                   'npm:firebase/firebase.js'
  }
});`

**Comment by inicio** [comment]
Thanks, @kieranfraser. I see my error now—I was referencing the library folder whereas I should have referenced the library folder's Javascript file!
