### ISSUE TITLE
Error when trying to use lodash in client part

### ISSUE THREAD

**Issue by hdurix** [ericmdantas/generator-ng-fullstack#239]
Hello,

I get an error when I try to use lodash in client part.

Here's my current configuration:

- stack: `fullstack`
- server: `node`
- client: `ng2`
- transpiler: `typescript`
- no http/2
- no different static server 

I added the following import:
`import * as _ from "lodash";`

Then, just for testing, I added:
`_.range(1, 50);`

Everything is compiling, but when the page is loaded, I get the following error:
`zone.js?rev=@@hash:405 Unhandled Promise rejection: (SystemJS) Unexpected token <`

I've figured out that the file `lodash.js` is not correctly loaded in the browser. Instead of having the javascript file, I get an html file (the application html body).

I tried on an other angular2 project, I don't have the same issue, so I don't know what is missing in my project.

Has anyone got an idea?

Thanks!

**Comment by ericmdantas** [comment]
Hello, @hdurix.

Where did you specify the lodash dep? In the `index.html` or `config.js`? Could you please share the file?

**Comment by hdurix** [comment]
I didn't specify any lodash dep, as it is declared in package.json (for server part), I thought it was enough so maybe it's the problem here.

After your answer, I tried to add the dep in `config.js` and `index.html` but I couldn't manage to make it work (same issue). How should I add the dep?

Thanks

**Comment by ericmdantas** [comment]
It should be added in the `config.js` file. It's just a systemjs file, so there are some explanations on how to use it out there, but by just doing:

```
map: { 'lodash' : 'node_modules/lodash/lodash.js' }
```

in your config.js should be enough. 

Let me know how it goes.

**Comment by hdurix** [comment]
No it wasn't enough but I finally found the correct way to do it.

In config.js: `'lodash' : 'npm:lodash/lodash.js'`

and in index.html: `<script src="./lodash/lodash.js?rev=@@hash"></script>` 

Thank you for your help!

**Comment by ericmdantas** [comment]
Awesome!
