### ISSUE TITLE
Prefer named exports insted of "export default" from templates.

### ISSUE THREAD

**Issue by frgomes** [ericmdantas/generator-ng-fullstack#242]
Employing ``export default`` defeats code refactoring.

    $ find . -type f -name '*.ts' | xargs fgrep -H -n 'export default' | fgrep -v /node_modules/
    ./server/api/todo/model/todo-model.ts:8:export default schema;
    ./server/api/todo/dao/todo-dao.ts:67:export default Todo;

**Comment by ericmdantas** [comment]
Right, but that should be done on all files, not only `.ts` files.

**Comment by ericmdantas** [comment]
Actually, I'll go ahead and close this, since it's a bit of a matter of taste. 

I mean, if you're really exporting something that should be "unique", I don't see any problem on that being the only thing exported in such file.
