### ISSUE TITLE
No Exported Member errors on new site

### ISSUE THREAD

**Issue by jelling** [ericmdantas/generator-ng-fullstack#244]
I created a new site per instructions but I get numerous errors (see below) from the stock code.

Here are my versions:

tsc -v
Version 2.1.5

web npm -v
3.10.9

web node -v
v7.1.0

The errors:

gulp
[16:41:55] Requiring external module babel-register
[16:41:56] Using gulpfile ~/Google Drive/Dev/Maverick/web/gulpfile.babel.js
[16:41:56] Starting 'client.build_ts'...
client/dev/index.ts(2,9): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/platform-browser-dynamic/index"' has no exported member 'bootstrap'.
client/dev/index.ts(3,9): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/http/index"' has no exported member 'HTTP_PROVIDERS'.
client/dev/todo/components/todo-cmp.ts(28,3): error TS2345: Argument of type '{ selector: string; templateUrl: string; styleUrls: string[]; directives: any[][]; providers: typ...' is not assignable to parameter of type 'Component'.
  Object literal may only specify known properties, and 'directives' does not exist in type 'Component'.
/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/forms/src/directives.d.ts(44,39): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/forms/src/directives.d.ts(48,48): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/forms/src/form_providers.d.ts(13,38): error TS2314: Generic type 'Type<T>' requires 1 type argument(s).
tests/client/todo/components/todo-cmp_test.ts(4,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'it'.
tests/client/todo/components/todo-cmp_test.ts(5,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'expect'.
tests/client/todo/components/todo-cmp_test.ts(6,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'describe'.
tests/client/todo/components/todo-cmp_test.ts(9,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'TestComponentBuilder'.
tests/client/todo/components/todo-cmp_test.ts(10,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'beforeEachProviders'.
tests/client/todo/components/todo-cmp_test.ts(14,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/index"' has no exported member 'provide'.
tests/client/todo/services/todo-service_test.ts(4,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'it'.
tests/client/todo/services/todo-service_test.ts(5,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'expect'.
tests/client/todo/services/todo-service_test.ts(6,3): error TS2305: Module '"/Users/jonhaven/Google Drive/Dev/Maverick/web/node_modules/@angular/core/testing/index"' has no exported member 'describe'.
[16:41:58] TypeScript: 15 semantic errors
[16:41:58] TypeScript: emit succeeded (with errors)
[16:41:58] Finished 'client.build_ts' after 1.97 s
[16:41:58] Starting 'client.watch'...
[16:41:58] Finished 'client.watch' after 36 ms
[16:41:58] Starting 'default'...
[16:41:58] Finished 'default' after 34 μs
[BS] Proxying: https://localhost:3333
[BS] Access URLs:
 -----------------------------------
       Local: https://localhost:3000
    External: https://10.0.0.24:3000
 -----------------------------------
          UI: http://localhost:3001
 UI External: http://10.0.0.24:3001
 -----------------------------------'

**Comment by jelling** [comment]
I upgraded to the latest version and this issue was resolved.

**Comment by ericmdantas** [comment]
Hey, @jelling!

Thanks for updating the generator. Good to know it's resolved! 👍
