### ISSUE TITLE
Directive not rendering

### ISSUE THREAD

**Issue by irthos** [ericmdantas/generator-ng-fullstack#245]
Hey this seems like a wicked fast workflow. Especially considering I've been on a more compile-during-dev setup. But I've made a directive, set it's source on index.html, and then added it to a state. I cannot see the thing render. Console.log only works above the directive definition, not within. I've switched out ng-route for ui.router if somehow that conflicts somewhere. 

Appreciate any help :)

**Comment by ericmdantas** [comment]
Hello, @irthos.

Stupid question, but are you using your directive anywhere? Like `<div my-directive-here></div>`?

**Comment by ericmdantas** [comment]
I'll go ahead and close it since it's not directly related to the generator, but feel free to send the errors you're getting.

**Comment by irthos** [comment]
yes, haha i've remembered to include the element. Seems to break when I add a template or templateURL to the returned object of the directive.

**Comment by irthos** [comment]
how do you recommend adding a view to the directive?
` function() {
        var _link = function(scope, element, attrs) {
          console.log(scope);
          console.log(element);
          console.log(attrs);
        };

        var _restrict = 'A';
        var _scope = {};
        var _replace = true;

        return {
          restrict: _restrict,
          template:'yo',
          replace: _replace,
		  scope: _scope,
          link: _link          
        };
      }
    `
