### ISSUE TITLE
SCSS over LESS?

### ISSUE THREAD

**Issue by jgodi** [ericmdantas/generator-ng-fullstack#25]
I vote for SCSS over LESS. Then we can use [Bourbon](http://bourbon.io), which is an amazing mixin library that makes CSS work cake. We can use `gulp-node-sass` to compile it, so users do not have to have Ruby installed.

**Comment by ericmdantas** [comment]
I vote both + the option of having no pre processor at all.

**Comment by jgodi** [comment]
:+1:

**Comment by dotch** [comment]
We should also consider using postcss as a way to deal with vendor prefixes, so people don't have to care about them on the css/preprocessing side.
E.g. We could add a postcss gulp task that adds vendor prefixes for the latest 2 versions of every major browser. (Basically only relevant for safari anyway...)

**Comment by ericmdantas** [comment]
@dotch, good. I have never used it, but even experienced people seem to like it better than the pre processors.

**Comment by aendrew** [comment]
Just do it like every other generator — give the user the option to select from a multitude of CSS preprocessors. A good implementation of this is `generator-react-fullstack`.  Would anyone be interested in me PRing this?

**Comment by ericmdantas** [comment]
@aendrew go for it :+1:

**Comment by aendrew** [comment]
@ericmdantas Cool, will do so sometime in the next week or two.

**Comment by ericmdantas** [comment]
@aendrew alrighty. I hope I'll have #6 done by then.

**Comment by elimence** [comment]
Hi, what's the status of this? I'd like to use Sass, but looks like that's still not an option during the process.

**Comment by ericmdantas** [comment]
Not an option for now, but it'd be good to have it.

I'm checking some stuff to see what fits in 1.9 - this is one of them.

**Comment by ericmdantas** [comment]
Target to 1.9.

**Comment by ericmdantas** [comment]
Remember to add the compilation in `build_css.js` and add the token in `watch.js`.

**Comment by ericmdantas** [comment]
The rest of the implementation depends on both https://github.com/ericmdantas/aliv/issues/22 and https://github.com/ericmdantas/aliv/issues/23.

**Comment by ericmdantas** [comment]
Done.
