### ISSUE TITLE
Bump Angular from 2.x to 4.x

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#254]

**Comment by ericmdantas** [comment]
http://angularjs.blogspot.com.br/2017/03/angular-400-now-available.html

**Comment by ericmdantas** [comment]
When trying to compile, I'm getting the following error:

```
node_modules/@angular/router/src/router_module.d.ts(140,41): error TS1110: Type expected.
```

**Comment by ericmdantas** [comment]
Updated `tsc` to `2.2.2` and now I'm getting:

```
node_modules/@angular/core/src/change_detection/differs/iterable_differs.d.ts(15,48): 
   error TS2304: Cannot find name 'Iterable'.
```

**Comment by luiscabanillas** [comment]
Anything on this? i'm thinking of using this generator but I want to use Angular 4.x, is this error still popping up?

**Comment by ericmdantas** [comment]
Hello, @luiscabanillas.

I tried to update it and got some typing errors (as described above) and I haven't touched it since then. I'm kinda busy these days, but I might be free this weekend, so I'll try to release a patch with the bump.

In the meantime, if you're interested, you can send a PR and I'll gladly merge it.

**Comment by ericmdantas** [comment]
I found https://github.com/angular/angular/issues/14595#issuecomment-289303911, which seems to fix the errors.

I'll release a new version in `master` and `next` with the bump.

**Comment by ericmdantas** [comment]
Versions published with the ng2 bump to 4.x.

```shell
# Install v1.9
$ npm i -g generator-ng-fullstack

# Install next (with some stuff from v1.10)
$ npm i -g generator-ng-fullstack@next
```

**Comment by ludoo0d0a** [comment]
Are these diffs the only things to do to upgrade an already generated app to 4.x ?
(^2.4.4-> ^4.1.0  + tsconfig.json:   "noImplicitAny": false,  "skipLibCheck": true )
https://github.com/ericmdantas/generator-ng-fullstack/commit/3c57a137632f5f004357030b57b0e736ac1a106b

**Comment by ericmdantas** [comment]
yup
