### ISSUE TITLE
Configurable Content Output 

### ISSUE THREAD

**Issue by Dev-Force** [ericmdantas/generator-ng-fullstack#257]
I nice idea would be to let the users create a configuration file with any changes they want to make to the naming and structure of the project before running the yo command

**Comment by ericmdantas** [comment]
Do you mean like https://github.com/ericmdantas/generator-ng-fullstack/issues/192?

**Comment by Dev-Force** [comment]
As I can tell no. Actually #192 could be a part of my suggestion. I suggest changing names of folders and files and whether or not to create daos controllers and views specifically for each.

**Comment by ericmdantas** [comment]
I see.

As of now, I have no idea how to make it without making the questions being "too much". If you've got any idea, let me know :smile:

**Comment by Dev-Force** [comment]
Thats what said. We dont need to achieve that through questions but through an optional configuration file. If someone wants to do that he wiil need to create a file with a specific name and put a json configuration in there. Then the generator will check if such a file exists in the working directory and inject the configuration if it does.

**Comment by ericmdantas** [comment]
Just out of curiosity: what would you like to change?

**Comment by ericmdantas** [comment]
Will be done in: https://github.com/ericmdantas/ngf/issues/1
