### ISSUE TITLE
TypeScript files are not actually watched in gulp watch task

### ISSUE THREAD

**Issue by dbilenkin** [ericmdantas/generator-ng-fullstack#258]
I noticed the gulp watch.js seems to be watching for html, css and ts files, but it looks like there is a bug in the ts line:

`_watchable.push(base.DEV + "**/.ts");`
`_watchable.push(base.DEV + "**/*.css");`
`_watchable.push(base.DEV + "**/*.html");`

Notice the `*` missing before the `.ts`. I'm assuming this is a mistake? Can I create a PR to add the `*`?

`_watchable.push(base.DEV + "**/*.ts");`

**Comment by ericmdantas** [comment]
Yup, this is a mistake.

Thanks for the PR!

**Comment by ericmdantas** [comment]
Fixed by a34c1304ba58dd32ecc6673e9adc15141d64e434. 

Thanks for the contribution.

**Comment by ericmdantas** [comment]
Also, both versions `1.9.5` and `next` were released with the fix.
