### ISSUE TITLE
Missing: SyncTestZoneSpec

### ISSUE THREAD

**Issue by astroanu** [ericmdantas/generator-ng-fullstack#260]
In the latest version i'm getting this error when running client.unit_test. Any idea on how to solve this?

````
16 03 2017 11:13:09.078:INFO [Chrome 56.0.2924 (Windows 10 0.0.0)]: Connected on socket OP5PF_Ojkmfhxm0CAAAA with id 95684974
Chrome 56.0.2924 (Windows 10 0.0.0) ERROR
  Uncaught Error: Missing: SyncTestZoneSpec
  at node_modules/zone.js/dist/jasmine-patch.js:43

`

**Comment by ericmdantas** [comment]
If you're using `ng2`, you're probably running into https://github.com/ericmdantas/generator-ng-fullstack/issues/101.

Closing as duplicated.

**Comment by astroanu** [comment]
so there's no fix for this now ?

**Comment by ericmdantas** [comment]
Nope, at the time there was too much going on the ng2 tests, even the core team was having trouble getting some tests running and/or keeping a given api stable - so I aborted the ng2 test task.

Nowadays the API might be more stable, but we'll need a release with the changes to the `*_test.ts` files, `karma.config.js` and so on.

**Comment by ericmdantas** [comment]
PR is welcome, by the way :smile:

**Comment by astroanu** [comment]
Cool, thanks. i'll take a look if i can get it to work somehow.
