### ISSUE TITLE
Is there a full resource generator with both client and server ? 

### ISSUE THREAD

**Issue by Oddadmix** [ericmdantas/generator-ng-fullstack#269]
I wanted to know whether there is a generator for both client and server. 

Also is there a way to configure the attributes for the model so that it would generate the right views  as well.

Thanks in advance.

**Comment by ericmdantas** [comment]
Hey, @Oddadmix.

Yes. This generator is able to work with the client and server together - simply choose the `fullstack` option in the questions asked.

As of right now, there's no custom params being passed to the view/model - it's a pretty dull file being created.
