### ISSUE TITLE
Angular Material

### ISSUE THREAD

**Issue by khwerhahn** [ericmdantas/generator-ng-fullstack#27]
Would also be a very nice alternative to bootstrap: https://material.angularjs.org. Its a very very awesome project.

Its being developed by the angular team, so there will be very nice support.

**Comment by ericmdantas** [comment]
That's a pretty good alternative. Specially because of the [google design](http://www.google.com.br/design/) layout.

How is the stability, though? They're about to release 0.9.0 - is that already a production ready version or should we wait until 1.0.0 comes out?

**Comment by khwerhahn** [comment]
@ericmdantas I think it would be wise to wait for the 1.0, but I don't think, that there are going to be major changes, just little fixes. They work pretty fast, so I think its not going to be long until the first major release.

**Comment by ericmdantas** [comment]
@khwerhahn, to be honest, I don't even like bootstrap that much. I'd rather do most things by hand, but sometimes we just don't have enough time :smile: 

There's just something that should be taken into consideration: the size of this dependency (how many Kbs will be downloaded?). I'm aware of all the caching stuff, but the first opening of our app can be a deal breaker.

I know bootstrap itself is pretty heavy, and that is a bad thing, specially when you want to have your app to open as fast on mobile devices compared to what it does in desktop. 

I mean, we still have very bad internet connection here in Brazil, so imagine the struggle to open up a heavy website.

Other than that, sounds good to wait for 1.0 =]

**Comment by khwerhahn** [comment]
Yeah size matters. Angular Material focuses on mobile with the iconic team putting in a lot of work. So I'm sure we'll be fine

**Comment by ericmdantas** [comment]
:+1:

**Comment by val-samonte** [comment]
+1 on this.

**Comment by remicastaing** [comment]
Keep an eye on the the upcoming [Material Design Lite](https://developers.google.com/web/tools/material-design-lite/).

**Comment by ericmdantas** [comment]
@remicastaing thanks!

**Comment by ericmdantas** [comment]
@remicastaing that was released, by the way.

Site: http://www.getmdl.io/
Github: https://github.com/google/material-design-lite

**Comment by georgeedwards** [comment]
Maybe something we can build into my new app # version? I am happy to do this. So you might have two new options, "do you want to add authentication?" and "would you like to use a front-end framework?" type thing?

**Comment by ericmdantas** [comment]
Sounds good, @georgeedwards.

I think it'd make more sense to have them separated, though - different branches and even different versions of the generator. Say 1.8 is for authentication and 1.9 is for material. And, yes, they'd be two different questions and they'd have to "mix" with the other different options the user chose. 

For example, user 1 chose:
- ng1
- client only app
- angular material
- no bootstrap

user 2 chose:
- ng2
- fullstack app
- no angular material
- bootstrap

user 3 chose:
- ng2
- fullstack app
- angular material
- no bootstrap

And on and on. Depending on the options chosen, we'll have to move a few things around, build, tests, index.html, etc.

**Comment by ericmdantas** [comment]
Out of scope.
