### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by catchlui** [ericmdantas/generator-ng-fullstack#270]
Hi ,

I am getting the below error,while starting the application
53:36] Starting 'client.compile_from_sass_to_css:dev'...
G:/nodejs/est/node_modules/@angular/common/src/directives/ng_class.d.ts(48,34): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/compiler/src/aot/compiler.d.ts(44,32): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/compiler/src/compile_metadata.d.ts(342,20): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/compiler/src/compile_metadata.d.ts(344,28): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/compiler/src/compile_metadata.d.ts(346,15): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/compiler/src/compile_metadata.d.ts(348,23): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/compiler/src/compile_metadata.d.ts(350,17): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/compiler/src/compile_metadata.d.ts(352,25): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/compiler/src/output/output_ast.d.ts(433,63): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(24,15): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/core/src/change_detection/differs/default_keyvalue_differ.d.ts(28,16): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/core/src/di/reflective_provider.d.ts(87,123): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/core/src/di/reflective_provider.d.ts(87,165): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/core/src/facade/lang.d.ts(12,17): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/core/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/http/src/headers.d.ts(52,59): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/http/src/url_search_params.d.ts(46,16): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/platform-browser/src/browser/browser_adapter.d.ts(79,33): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/platform-browser/src/dom/dom_adapter.d.ts(97,42): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/platform-browser/src/dom/dom_renderer.d.ts(22,37): error TS2304: Cannot find name 'Map'.
G:/nodejs/est/node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts(11,30): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/@angular/platform-browser/src/dom/shared_styles_host.d.ts(22,30): error TS2304: Cannot find name 'Set'.
G:/nodejs/est/node_modules/rxjs/Observable.d.ts(69,60): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
tests\client\todo\components\todo-cmp_test.ts(1,1): error TS6053: File 'G:/nodejs/est/typings/index.d.ts' not found.
tests\client\todo\components\todo-cmp_test.ts(35,1): error TS2304: Cannot find name 'describe'.
tests\client\todo\components\todo-cmp_test.ts(36,3): error TS2304: Cannot find name 'describe'.
tests\client\todo\components\todo-cmp_test.ts(37,5): error TS2304: Cannot find name 'it'.
tests\client\todo\components\todo-cmp_test.ts(43,4): error TS2304: Cannot find name 'expect'.
tests\client\todo\components\todo-cmp_test.ts(46,5): error TS2304: Cannot find name 'it'.
tests\client\todo\components\todo-cmp_test.ts(50,4): error TS2304: Cannot find name 'spyOn'.
tests\client\todo\components\todo-cmp_test.ts(52,4): error TS2304: Cannot find name 'expect'.
tests\client\todo\components\todo-cmp_test.ts(55,5): error TS2304: Cannot find name 'it'.
tests\client\todo\components\todo-cmp_test.ts(65,5): error TS2304: Cannot find name 'it'.
tests\client\todo\services\todo-service_test.ts(1,1): error TS6053: File 'G:/nodejs/est/typings/index.d.ts' not found.
tests\client\todo\services\todo-service_test.ts(7,1): error TS2304: Cannot find name 'describe'.
tests\client\todo\services\todo-service_test.ts(8,3): error TS2304: Cannot find name 'describe'.
tests\client\todo\services\todo-service_test.ts(9,5): error TS2304: Cannot find name 'it'.
tests\client\todo\services\todo-service_test.ts(10,3): error TS2304: Cannot find name 'expect'.
[23:53:39] TypeScript: 38 semantic errors

**Comment by ericmdantas** [comment]
If you already have `typings` installed globally (npm i -g typings), simply run `typings install` and try again.
