### ISSUE TITLE
[koa + typescript] Error when compiling server code

### ISSUE THREAD

**Issue by steadycoding** [ericmdantas/generator-ng-fullstack#272]
Steps to reproduce:
Windows 10
npm 4.5.0 and node.js 7.8.0
Have installed the ngfullstack generator
From cmd
1. Create directory \dev\ngFullStack
2. cd into directory
3. yo ng-fullstack
4. Options: appName, user, user@user.com, fullstack, github or bitbucket, ng2, sass, node, koa, , typescript, yes, yes, no
5. npm run dev

Comments:
I have repeated these steps using C drive only and from a separate data drive with the same results.
Also fails on Next generator

**Comment by ericmdantas** [comment]
Hey, @steadycoding.

If I remember correctly, typescript and koa weren't getting along very well. Can you please post the whole error message? I'm pretty sure that's the error.

**Comment by steadycoding** [comment]
@ericmdantas Yep. Since then I've tried all sorts of combinations.
The error that I get when I run the generator with these options 
![image](https://cloud.githubusercontent.com/assets/17366068/24991673/7f6e3e4a-1fd1-11e7-8354-80e450741f70.png)
**npm run dev** error: "tsc && concurrently "nodemon ./server/index --watch server" "gulp""  
**npm start** error: "node server/index"
**gulp** error:  a browser tab opens with the index.html page and a todo input field, but it's not responsive even though the terminal is listening.

then without typescript
![image](https://cloud.githubusercontent.com/assets/17366068/24991954/5473689e-1fd3-11e7-9bd7-3d69a7424c3d.png)

**npm run dev** gives me this 
![image](https://cloud.githubusercontent.com/assets/17366068/24992106/60675d44-1fd4-11e7-8183-598dd85fbadb.png)
![image](https://cloud.githubusercontent.com/assets/17366068/24992175/c669bec0-1fd4-11e7-9a8e-1c49307d1e1b.png)
![image](https://cloud.githubusercontent.com/assets/17366068/24992222/0a2d188c-1fd5-11e7-9779-86b38b1cacac.png)
![image](https://cloud.githubusercontent.com/assets/17366068/24992304/8e4e8c54-1fd5-11e7-82de-a6c27c562f4a.png)
I then ran npm i -g istanbul mocha babel gulp-cli and npm install -g typescript typings and typings install
then I ran npm run dev again in both projects.
With Typescript
![image](https://cloud.githubusercontent.com/assets/17366068/24992593/19b1ce5e-1fd7-11e7-8422-9499b3bf6981.png)
Without Typescript
![image](https://cloud.githubusercontent.com/assets/17366068/24992609/3cf73bc4-1fd7-11e7-894c-6217f867ce5d.png)
I guess the issues are that typescript is not really working and the getting started page should move the npm run dev commands to the end after the using node/go/typescript sections. 

I'm glad I came back and gave it another shot. The generator is really nice when it works. Bummed to be missing typescript.

**Comment by ericmdantas** [comment]
Thanks for providing such details!

So, yeah, that's what I expected. Koa and Typescript are not working together - the other combinations are doing fine.

I'll check what's available in terms of typings for Koa and release a patch with it. If you'd like, feel free to send a PR :smile:

**Comment by ericmdantas** [comment]
Might be tackled in #289
