### ISSUE TITLE
npm run dev does not works on a newly generated app.

### ISSUE THREAD

**Issue by dassiorleando** [ericmdantas/generator-ng-fullstack#274]
Hi @all,
Hi just generate a new app to use it as a starter of my project, but it does not work at all.

**Details**
![capture d ecran 2017-04-20 a 17 37 33](https://cloud.githubusercontent.com/assets/7150752/25242121/79a2f562-25f0-11e7-8813-72bb0808919f.png)

**Error**
`DassiMacBook:free-bloog dassiorleando$ npm run dev

> freeblood@0.0.1 dev /Users/dassiorleando/stuffs/freestyle/free-bloog
> tsc && concurrently "nodemon ./server/index --watch server" "gulp"

sh: concurrently: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! freeblood@0.0.1 dev: `tsc && concurrently "nodemon ./server/index --watch server" "gulp"`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the freeblood@0.0.1 dev script 'tsc && concurrently "nodemon ./server/index --watch server" "gulp"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freeblood package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc && concurrently "nodemon ./server/index --watch server" "gulp"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freeblood
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freeblood
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dassiorleando/.npm/_logs/2017-04-20T16_35_09_358Z-debug.log
`
Thanks in advance.

**Comment by ericmdantas** [comment]
Hey there, @dassiorleando.

That's a weird error, it's like it never ran `npm install` for you. Do you mind running it manually and trying again?

**Comment by dassiorleando** [comment]
I done this: 
`npm install -g concurrently` : Install concurrently globaly.
And looks like it is working.

**Comment by ericmdantas** [comment]
Well, good to know.

`concurrently` was supposed to be installed locally only, but.. at least its working. Thanks, @dassiorleando.

**Comment by dassiorleando** [comment]
Welcome.
The better is to run: `npm install --dev`
Not yet mensionded in the getting started.

To install all dev dependencies locally, concurrently and others one will be installed too.

**Comment by ericmdantas** [comment]
But that's done automagically for you right after you answer the questions - `yo` calls `npm install` under the hood.

**Comment by dassiorleando** [comment]
But dev dependencies was not.
Weird I know.
