### ISSUE TITLE
No option to add route directly?

### ISSUE THREAD

**Issue by aditya61085** [ericmdantas/generator-ng-fullstack#275]
I didnt find command to directly add route to application with components. Is there any?

**Comment by ericmdantas** [comment]
Nope.

What client framework are you using?

**Comment by aditya61085** [comment]
I am using angular 2.

I was looking something similar to https://angular-fullstack.github.io/generators/route/
I just switched from this as they dont have ang2 support yet.

**Comment by ericmdantas** [comment]
I see.

Right now for ng2, in the todo app, the route lives in the same folder as the component. I'll have to check out how the other client frameworks prefer to have the routes separated, so I can implement the subgenerator.

**Comment by ericmdantas** [comment]
Will be solved in each framework - also `v2`.
