### ISSUE TITLE
test db helper - mongoose connection

### ISSUE THREAD

**Issue by ludoo0d0a** [ericmdantas/generator-ng-fullstack#276]
Tests should wait for Mongoose connection.
This would be better :

```js
import dbJson from "./db.json";
import Promise from 'bluebird';

exports.setupMongoose = (mongoose, done) => {
  mongoose.Promise = Promise;  //Add promise
  mongoose.models = {};
  mongoose.connection.on("error", () => {});
  mongoose.connect(dbJson.db.test.url, done);  //pass done
}
```

and in xxx_test.js

```js
    before((done) => {
        setupMongoose(mongoose, done);
    });
```

**Comment by ericmdantas** [comment]
Hey, @ludoo0d0a. Nice catch. 

If you feel like giving it a shot, feel free to do so. I'll only have free time on the weekend.

**Comment by ericmdantas** [comment]
Since it's just enhancement, it'll be merged into master when `v1,10` is done.

Thanks once again.

**Comment by ludoo0d0a** [comment]
you're welcome.
Nice to see that fixes are fast :+1:

**Comment by ericmdantas** [comment]
:smile:
