### ISSUE TITLE
Todo app isnt' saving to Mongo's DB

### ISSUE THREAD

**Issue by TheBrenny** [ericmdantas/generator-ng-fullstack#277]
I've been doing ~7hours of non-stop Googling and research about why my Todo app isn't replicating what is visible in the Wikis.

I generate as follows:
```
What is the name of your app? tapman
What is your username? TheBrenny
What is your email (used in your package.json)? thebrenny@brennytizer.com.au
Which stack do you want? fullstack
Which Git repository hosting service are you using? github
Which framework do you want to use in the client side? vue2
Which CSS pre-processor do you want to use? sass
What language do you want in the server side? node
Which framework do you want to use in server side? express
Which transpiler do you want to use in server side? node
Is it going to be a secure app (HTTP/2)? No
Do you want to keep tests in a different folder? Yes
Do you want to use a different static server? Such as NGINX, Apache, IIS, etc? No
```

I've generated using Angular as well, and have come to the conclusion that it's an issue with Vue. For some reason, adding an item doesn't update the database, and hence deleting an item won't throw an error because it's not reaching the database. I'm going to look through the code side-by-side to try and find any discrepancies, but I feel that lodging an issue would speed up the process of fixing it.

**Comment by ericmdantas** [comment]
Hello, @TheBrenny.

Right, so a couple questions: 
- Is the information being shown in the `network` tab? 
- Is the `mongod` service running? 

Keep in mind that Angular and Vue choice does not affect the server side, so if there's a problem, it's just in the client - either the info is not getting there, or the db is not up yet.

**Comment by TheBrenny** [comment]
Sorry, I should've been more clear: I'm fairly certain it's an issue on the client-side. I'm not gonna lie, I really have no clue why this is happening... 😄 

Onto your questions:
1. Yes. See the picture below.
2. AFAIK, yes. As a foreground service, so I have an open Command Prompt.

![image](https://cloud.githubusercontent.com/assets/1498923/25882464/bca865a8-3582-11e7-87ea-6c6f8201f9e4.png)

**Comment by TheBrenny** [comment]
If it's worth anything, here's the output from the Terminal and Command Prompt when running the Vue version and adding three items:
![image](https://cloud.githubusercontent.com/assets/1498923/25884132/57a17944-358f-11e7-8acc-af5fc568dd86.png)


Similarly, however running Angular:
![image](https://cloud.githubusercontent.com/assets/1498923/25884184/b018760e-358f-11e7-8bec-18f2216edf25.png)

It's starting to look like the issue isn't it the saving functionality, but the initial `GET`. The items I create in Vue show up in Angular (if that makes sense)... Sort of seemed like a slight red herring... 🐠

**Comment by TheBrenny** [comment]
Found the issue. Vue 2 no longer has the `ready` function. It's been replaced by `mounted`. That's why I was never receiving the latest posts. ([See this SO answer for future reference](http://stackoverflow.com/questions/40209443/vue-js-ready-function-is-not-triggered#answer-40209796))

Wowee. What an adventure!

**Comment by ericmdantas** [comment]
Haha, awesome catch, @TheBrenny.

Thanks for all the info!
