### ISSUE TITLE
dynamic roles based authorisation

### ISSUE THREAD

**Issue by khwerhahn** [ericmdantas/generator-ng-fullstack#28]
I would also suggest to include [connect-roles](https://github.com/ForbesLindesay/connect-roles). I'm sure that I'm not the only one who has to use roles in their projects. It mixes in perfectly with passport.

I'm sure it would help a lot of projects

**Comment by ericmdantas** [comment]
I was thinking and this probably doesn't belong to the core, more like a specific implementation, for the type of system that really needs a authentication and suchs.

Let me know if you disagree.

For now, I'm closing this
