### ISSUE TITLE
Task 'client.build:dist' is not in your gulpfile

### ISSUE THREAD

**Issue by alexri89** [ericmdantas/generator-ng-fullstack#283]
Hi there,

I installed a server-side application via your yo-generator (nodejs + typescript). After I ran npm run build-dist I came across the error message "Task 'client.build:dist' is not in your gulpfile". 

Installation
- Server only, Nodejs
- Typescript
- Newest version of generator (just updated earlier today)

How can I fix that?

Cheers,
Alex

**Comment by ericmdantas** [comment]
Hey, @alexri89.

For server-side builds (with typescript), the ideal scenario would be the IDE to build it for you on save. If that's not possible, then you can call the `gulp server.compile_tsc` directly.

But, I agree that can be improved. I'll release a patch soon.

**Comment by ericmdantas** [comment]
`v1.9.19` released with the fix.

Changes:

- added the use of `server.compile_tsc` in `package.json` when the user selects server only and typescript
- `tasks/server/build_tsc.js` has a new `dest` path (`./server`)
