### ISSUE TITLE
Name convention problems upon using generator

### ISSUE THREAD

**Issue by barajagmartin** [ericmdantas/generator-ng-fullstack#285]
Hi!

When I use the ngf generator for generating for example a component for Angular 2, it doesn't seem to follow the style guide from [Angular Style Guide](https://angular.io/guide/styleguide#components). Is there a reason for this?

**Comment by ericmdantas** [comment]
Hey, @barajagmartin.

This is mostly because when the generator was created there was no such style guide for Angular2 yet. So some stuff were just kept as they were.

Are there any specific styles you'd like to see implemented?

**Comment by barajagmartin** [comment]
Okay! Hmm, if I wrote `$ ngf g component car --feat car` as in [the ngf wiki](https://github.com/ericmdantas/ngf/wiki/API) it would be nice if:

- the "feature folder" would be called _car_
- the component would be called: _car.component.ts_
- the class would be called: _CarComponent_

The same would go for services etc.

Do you understand what I mean?

**Comment by ericmdantas** [comment]
Yup, sounds good.

**Comment by barajagmartin** [comment]
Also, in [service](https://github.com/ericmdantas/generator-ng-fullstack/blob/master/service/templates/ng2/service.ts) for example, the name is MyService instead of the name when being generated.

Thanks!

**Comment by ericmdantas** [comment]
Will be solved in https://github.com/ericmdantas/ngf/issues/4
