### ISSUE TITLE
No scss-file is generated when using ngf generate

### ISSUE THREAD

**Issue by barajagmartin** [ericmdantas/generator-ng-fullstack#286]
When I run `ngf g cmp, some.component --ft someFeature` the style file generated is only a css-file. Would it be possible to generate a scss-file as in the 'todo example app'?

_Edit: When using Angular 2_

**Comment by barajagmartin** [comment]
Made a pull-request https://github.com/ericmdantas/generator-ng-fullstack/pull/287

**Comment by ericmdantas** [comment]
Oops, it should be that way. I'll release a patch with the fix.

**Comment by ericmdantas** [comment]
`v1.9.20` published.
