### ISSUE TITLE
No Showing On Yeoman

### ISSUE THREAD

**Issue by ybchoo** [ericmdantas/generator-ng-fullstack#296]
Hi Everyone
This is a great project but when I search this 
generator-ng-fullstack on yeoman.io is no longer listed.
Is there some issue?

**Comment by ericmdantas** [comment]
Hey, @ybchoo.

Sorry for taking so long to answer, I'm on vacation. As for the reported issue, I don't know what's wrong, but I couldn't find it either. I'll see what I can find about it and I'll let you know.

Thanks!

**Comment by ericmdantas** [comment]
I have added the `yeoman-generator` string in the package.json's keyword. That should do the trick!

Thanks for letting me know, @ybchoo.
