### ISSUE TITLE
Troubles continued from #297

### ISSUE THREAD

**Issue by dgleba** [ericmdantas/generator-ng-fullstack#299]
Continuing from #297 

I got:
```
> ngf-k7017@0.0.1 start-server /srv/file/test/vc/ngf-k7017
> node server/index
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module 'morgan'
```
Also more missing as I fixed one after the other.

I did:

```
 npm i --save morgan
 npm i --save helmet
 npm i --save mongoose
 
```

That got it running.

Then I didn't see entered todo's - just an empty line. See pic below.

![2019-11-24 21_19_32-Robo 3T - 1 3](https://user-images.githubusercontent.com/4622715/69507680-5a254f80-0f01-11ea-999f-eafed175f7cd.jpg)

There is data in mongodb.

![2019-11-24 21_20_01-Robo 3T - 1 3](https://user-images.githubusercontent.com/4622715/69507710-6f01e300-0f01-11ea-923f-f5aa6d8d9b73.jpg)

Maybe I am doing something wrong.

**Comment by ericmdantas** [comment]
Hey there, @dgleba!

The error is in the `Todo constructor` in the `todo-cmp.vue` file. There's no todo object being passed to the constructor and no assignment happening. Here's how to fix it:

```ts
// wrong
class Todo {
  constructor() {
    this._id = undefined
    this.todoMessage = ""
  }

  isValid() {
    return !!this.todoMessage
  }
}
```

```ts
// right
class Todo {
  constructor(t) {
    this._id = undefined
    this.todoMessage = ""

   Object.assign(this, t) 
  }

  isValid() {
    return !!this.todoMessage
  }
}
```

I'll release a fix in a moment.

**Comment by ericmdantas** [comment]
`v2.0.18` released. Thanks for bringing up the issue, @dgleba!

**Comment by dgleba** [comment]
Thanks for looking into it!

**Comment by dgleba** [comment]
I had to 
``` 
 npm i --save morgan
 npm i --save helmet
 npm i --save mongoose
```
How can that be added to the system? 
Can you comment?

**Comment by ericmdantas** [comment]
Sure, I'll take a look when I get home.
