### ISSUE TITLE
How about deploying on Docker 

### ISSUE THREAD

**Issue by programming-kid** [ericmdantas/generator-ng-fullstack#42]
Wow m excited to have found this i have been using https://github.com/DaftMonk/generator-angular-fullstack as my primary generator to start any project , but it is now almost dead 

I found this while researching for my new generator. ```ng-fullstack``` looks kinda hot & promising  , but not production ready according to me , while features are being added to this generator i wanted to suggest to integrate Docker with generator for deploying

thanks

**Comment by ericmdantas** [comment]
Hey there! And that's a very good idea!

I still have to try my luck with docker, but it's definetely worth having this feature.

As always, PRs are welcome! =]

**Comment by ericmdantas** [comment]
As for the production ready status, yeah, I'd say play with it a bit but don't go very far just yet. We're still messing around here and there trying to find the best ways to implement and reuse stuff.

**Comment by programming-kid** [comment]
i am too messing around with docker, i have project on fullstack i will be migrating from it soon , i am just evaluating my options here, keep up the good work :+1:

**Comment by ericmdantas** [comment]
Decided not to do that in the core, thanks for the suggestion, though :smile:
