### ISSUE TITLE
Project created in parent directory

### ISSUE THREAD

**Issue by FreakTheMighty** [ericmdantas/generator-ng-fullstack#44]
I'm not sure if I'm missing something, but when I run the generator the project is created in the parent. For example, 
```
mkdir /tmp/whoop
cd /tmp/whoop
yo ng-fullstack
```

The project is created in `/tmp`

**Comment by FreakTheMighty** [comment]
My mistake, there was a `.yo-rc.json` in the tree, removing it fixed the problem.

**Comment by ericmdantas** [comment]
That's weird. Was the ```.yo-rc.json``` generated by ```yo ng-fullstack``` or was it already there?

**Comment by FreakTheMighty** [comment]
I must have run the generator in tmp to start. I cleaned up visible files,
but not dot files.

**Comment by ericmdantas** [comment]
Alright =]
