### ISSUE TITLE
Gulp Error: Unrecognised input. Possibly missing opening

### ISSUE THREAD

**Issue by FreakTheMighty** [ericmdantas/generator-ng-fullstack#45]
When I run gulp in the root of the project I get this error:

```
[17:08:08] Working directory changed to ~/Code/time-tracker
[17:08:09] Using gulpfile ~/Code/time-tracker/gulpfile.js
[17:08:09] Starting 'del_temp'...
[17:08:09] Finished 'del_temp' after 4.51 ms
[17:08:09] Starting 'partials:temp'...
[17:08:09] Starting 'views:temp'...
[17:08:09] Starting 'imgs:temp'...
[17:08:09] Starting 'fonts:temp'...
[17:08:09] Starting 'html,css,js:temp'...
[17:08:09] Starting 'bower'...
[17:08:09] Starting 'browser_sync'...
[17:08:09] Finished 'browser_sync' after 279 μs
[17:08:09] Finished 'partials:temp' after 78 ms
[17:08:09] Finished 'fonts:temp' after 72 ms

/Users/jvanderdoes/Code/time-tracker/node_modules/gulp-less/node_modules/accord/node_modules/when/lib/decorators/unhandledRejection.js:80
		throw e;
		      ^
Error: Unrecognised input. Possibly missing opening '{' in file /Users/jvanderdoes/Code/time-tracker/css/styles.min-04deeee6.css line no. 5
```

I'm not very familiar with gulp, but it appears the less task is attempting to glob a directory that isn't there with this line `var _less = DEV_DIR + 'css/**/*.less';`.

**Comment by ericmdantas** [comment]
Hello.

Do you have anything inside your ```client/dev/css``` folder?

**Comment by FreakTheMighty** [comment]
@ericmdantas I do

```
$ ls client/dev/css/
events.less			media_queries.less
fonts.less			position.less
frameworks_overrides.less	styles.less
```

**Comment by ericmdantas** [comment]
Alright, I'll take a look at it when I get home.

**Comment by ericmdantas** [comment]
I did get the error at first, but then it didn't happen again.

**Comment by ericmdantas** [comment]
Turns out the problem is with bootstrap's version ```3.3.5``` version.

Could you please change the version of your bootstrap in the bower.json?

From:

```
"bootstrap": "~3.3.1",
```

To: 

```
"bootstrap": "3.3.1",
```

**Comment by ericmdantas** [comment]
Also, here's the [bootstrap issue](https://github.com/twbs/bootstrap/issues/16663).

**Comment by FreakTheMighty** [comment]
:+1: that worked, thank you

**Comment by ericmdantas** [comment]
Good to know =]

**Comment by aendrew** [comment]
Note, this was a breaking issue for me installing via `npm install -g generator-ng-fullstack` as per the documentation. Given it's now fixed in `master`, I'd very much recommend doing a new release ASAP so as not to dissuade new users, or at least signpost this issue in the README.

Super cool generator otherwise! Looking forward to using it!

**Comment by ericmdantas** [comment]
@aendrew Hello, thanks!

It should be fixed now, it's been a while as `bootstrap 3.3.1` in the bower.json.

**Comment by aendrew** [comment]
Odd; I got 1.4.0 from a NPM install, but now have 1.5.1-0 via `npm install generator-ng-fullstack@latest`. Not sure why it gave me the older version (maybe you need to do a `npm publish`? No idea.); apologies, working fine now, please disregard!

**Comment by ericmdantas** [comment]
That's probably because of the pre-release thing, I'm moving some things around and I'll release the 1.5 soon.
