### ISSUE TITLE
Gulpfile missing babel declaration, doesn't watch views

### ISSUE THREAD

**Issue by dmitryfd** [ericmdantas/generator-ng-fullstack#47]
Any execution of compile:babel fails, as this line is missing and babel variable is not declared.

    var babel = require('gulp-babel');

Also, page doesn't reload on changes in views' html, because _views variable (although declared) doesn't seem to be added to _watchable array.

     _watchable.push(_views);

Finally, I believe that first task executed upon changes (on watch) should be del_temp instead of compile:babel. It doesn't really make sense in that context and throws ENOENT on file changes, since the previous __tmp was not deleted.

    return gulp.watch(_watchable, ['compile:babel', 'bower', 'build_temp', 'browser_sync']);
    ->
    return gulp.watch(_watchable, ['del_temp', 'bower', 'build_temp', 'browser_sync']);

These changes fixed the errors I was having with live updating the files.
Please, correct me if I am misunderstanding smth here.

EDIT: I submitted a pull request for your convenience.

**Comment by ericmdantas** [comment]
I might've been cleaning up some stuff and forgot this, thanks for the PR!
