### ISSUE TITLE
Switch from bower to npm

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#49]

**Comment by Kageetai** [comment]
What is that supposed to mean? How are you supposed to switch from one to the other? There two different package managers for different purposes.

**Comment by ericmdantas** [comment]
Hello, @Kageetai. 

I was in a conference in Porto Alegre (Brazil) and Laurie Voss was talking about how npm is planning to work better (with less tooling) for frontend development - so I thought I'd open an issue to not forget about that.

But don't worry, we're not there yet :smile:

**Comment by Kageetai** [comment]
Oh okay, I didn't know about that, sounds interesting...

**Comment by ericmdantas** [comment]
Definetely, not to mention that bower just can't keep up with npm. The only thing that holds most people back is the tooling that involves bringing node modules to the client side. 

But it looks like they're working on it.

**Comment by aendrew** [comment]
In shiny new Angular 2 land, and especially when we have stuff like Webpack and TypeScript precompiling/transpiling/whatever everything anyway, there really isn't any reason at all to continue using Bower. Bower was mainly useful when we're using stuff like Wiredep to insert dependencies so as to be consumed as globals via script tags; now that all the module loading is done withn the script itself, it's far less necessary. You also don't have to worry about stuff like Bower's somewhat-annoying dependency resolution system.

I'd consider doing a PR that accomplishes this if there's enough interest; don't think it'd take very long.

**Comment by ericmdantas** [comment]
Pretty much. 

For ng2 I have been using npm only, as a package manager, and system only for loading the client-side modules. No fancy stuff like webpack, jspm, rollup or anything else. 

It's been pretty good so far.

**Comment by JonahTurnquist** [comment]
+1. Bower is a thing of the past, now with the npm upgrades. It should really be removed from this generator

**Comment by ericmdantas** [comment]
By the way, the only client that is using bower is `ng1`. 

`ng2`, `vue` and `aurelia` are all being implemented with `npm` as the package manager.

**Comment by ericmdantas** [comment]
I'll go ahead and close this because ng1 is the only one using it, as said above, all the new stuff for client are using npm/jspm.
