### ISSUE TITLE
server.ts won't start

### ISSUE THREAD

**Issue by madskonradsen** [ericmdantas/generator-ng-fullstack#53]
node index throws error. I guess the server.ts isn't being transpiled

node index

module.js:339
    throw err;
    ^

Error: Cannot find module './server/server'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mads/Desktop/test/index.js:1:63)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)

**Comment by ericmdantas** [comment]
Hello.

Could you try with `npm start`?

**Comment by madskonradsen** [comment]
Same issue... But npm start is also just a "shortcut"...


mads$ npm start

> douglas@0.0.1 start /Users/mads/Desktop/test
> node index

module.js:339
    throw err;
    ^

Error: Cannot find module './server/server'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/mads/Desktop/test/index.js:1:63)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)

**Comment by ericmdantas** [comment]
Alright, got the bug.

The `tsconfig.json` file is misplaced. I'll fix it and release a version you'll be able to install via:

```shell
$ npm i -g generator-ng-fullstack@latest
```

**Comment by ericmdantas** [comment]
Alright, `1.5.2-0` is published.

Install it:

```shell
$ npm i -g generator-ng-fullstack@latest
```

When you're done installing, just run:

```shell
$ gulp
```

```shell
$ tsc
```

```shell
$ npm start
```

Also, make sure you already have mongodb running.

**Comment by madskonradsen** [comment]
I get a lot of errors with tsc... I assume it has to do with some setting?

Madss-MacBook-Pro:test mads$ cd server
Madss-MacBook-Pro:server mads$ tsc
api/todo/controller/todo.controller.ts(8,10): error TS2339: Property 'getAll' does not exist on type 'Model<Document>'.
api/todo/controller/todo.controller.ts(9,28): error TS2339: Property 'status' does not exist on type 'Object'.
api/todo/controller/todo.controller.ts(10,29): error TS2339: Property 'status' does not exist on type 'Object'.
api/todo/controller/todo.controller.ts(14,23): error TS2339: Property 'body' does not exist on type 'Object'.
api/todo/controller/todo.controller.ts(17,10): error TS2339: Property 'createTodo' does not exist on type 'Model<Document>'.
api/todo/controller/todo.controller.ts(18,27): error TS2339: Property 'status' does not exist on type 'Object'.
api/todo/controller/todo.controller.ts(19,29): error TS2339: Property 'status' does not exist on type 'Object'.
api/todo/controller/todo.controller.ts(23,19): error TS2339: Property 'params' does not exist on type 'Object'.
api/todo/controller/todo.controller.ts(26,8): error TS2339: Property 'deleteTodo' does not exist on type 'Model<Document>'.
api/todo/controller/todo.controller.ts(27,23): error TS2339: Property 'status' does not exist on type 'Object'.
api/todo/controller/todo.controller.ts(28,27): error TS2339: Property 'status' does not exist on type 'Object'.
api/todo/dao/todo.dao.ts(4,23): error TS2307: Cannot find module 'bluebird'.
api/todo/model/todo.model.ts(10,16): error TS2348: Value of type 'typeof Schema' is not callable. Did you mean to include 'new'?
commons/socket/socket-events.ts(5,12): error TS2339: Property 'on' does not exist on type 'Object'.
commons/socket/socket-events.ts(6,18): error TS2339: Property 'on' does not exist on type 'Object'.
commons/socket/socket-events.ts(7,16): error TS2339: Property 'emit' does not exist on type 'Object'.
config/db.conf.ts(6,26): error TS2307: Cannot find module '../constants/db.json'.
config/routes.conf.ts(5,25): error TS2307: Cannot find module 'morgan'.
config/routes.conf.ts(6,29): error TS2307: Cannot find module 'body-parser'.
config/routes.conf.ts(7,32): error TS2307: Cannot find module 'express-content-length-validator'.
config/routes.conf.ts(8,25): error TS2307: Cannot find module 'helmet'.
config/routes.conf.ts(15,21): error TS2339: Property 'use' does not exist on type 'Object'.
config/routes.conf.ts(15,29): error TS2339: Property 'static' does not exist on type 'Object'.
config/routes.conf.ts(16,21): error TS2339: Property 'use' does not exist on type 'Object'.
config/routes.conf.ts(17,21): error TS2339: Property 'use' does not exist on type 'Object'.
config/routes.conf.ts(18,21): error TS2339: Property 'use' does not exist on type 'Object'.
config/routes.conf.ts(19,21): error TS2339: Property 'use' does not exist on type 'Object'.
routes/index.ts(11,9): error TS2339: Property 'route' does not exist on type 'Object'.
routes/index.ts(14,10): error TS2339: Property 'use' does not exist on type 'Object'.
typings/node/node.d.ts(212,21): error TS2304: Cannot find name 'Map'.
typings/node/node.d.ts(221,21): error TS2304: Cannot find name 'Set'.
typings/node/node.d.ts(231,25): error TS2304: Cannot find name 'WeakMap'.
Madss-MacBook-Pro:server mads$

**Comment by ericmdantas** [comment]
Yeah, probably some minor thing.

Other than that, is it working now?

**Comment by madskonradsen** [comment]
Yeah it's working!

**Comment by ericmdantas** [comment]
Alright, cool!

I got this bunch of messages too, but my pc just gave up on me, so I dont know when I'll be able to fix it. Probably somewhere around wednesday.

If you know what is wrong, either let me know or submit a PR.

**Comment by ericmdantas** [comment]
Since the server is starting just fine, I'm closing this and opening one to fix the typings.

Thanks for the feedback!
