### ISSUE TITLE
go get error in windows

### ISSUE THREAD

**Issue by manjeshpv** [ericmdantas/generator-ng-fullstack#57]
In installed generator, then generated project, npm and bower installed.

Now I'm getting a error while installing `go get`
```sh
main.go:5:2: cannot find package "github.com//gorest/server/routes" in any of:
        C:\Go\src\github.com\gorest\server\routes (from $GOROOT)
        c:\Users\ManjeshV\src\github.com\gorest\server\routes (from $GOPATH)
```
then I changed imports in `main.go`
from `	"github.com//gorest/server/routes"`
to  `	"github.com/gorest/server/routes"`

Still package is not resolving. I'm unable to findout https://github.com/gorest/server/routes

Update 1: I'm a beginner, Now I get to know its importing my own project routes. But still I'm not able to resolve. I guess it might be like `github.com/manjeshpv/gorest/server/routes` In this `gorest` in project name and `manjeshpv` is username

**Comment by ericmdantas** [comment]
Did you get it to run with your name in it?

**Comment by ericmdantas** [comment]
Closing this in favor of #46.
