### ISSUE TITLE
Typescript in client (for ng1)?

### ISSUE THREAD

**Issue by bbartlett** [ericmdantas/generator-ng-fullstack#58]
Any plans for Typescript support in the client in the Angular1 templates?  I saw that issue #37 says "server only for now", but looks like Typescript support is creeping in on the ng2 templates. Any plans for ng1 support as well?

**Comment by ericmdantas** [comment]
Hello, @bbartlett.

Typescript for ng1 isn't in the schedule, to be honest.

I'm looking to finish the ng2 integration with ts first, get 1.6 ready to go, and then I might be able to take a look at the integration for ng1. 

Having said that, PRs are always welcome, if you want to start something for ng1, let me know and I'll help you.

**Comment by bbartlett** [comment]
Didn't think so, but was hoping ...

I need to improve my use of Typescript on the Angular side a bit, but once I have something reasonably decent, I'll reach back out to you to contribute it back.

**Comment by ericmdantas** [comment]
Alright! :smile:

**Comment by ericmdantas** [comment]
Closing this, let me know if you have anything going.
