### ISSUE TITLE
Syntax error when running "node start"

### ISSUE THREAD

**Issue by tmundt** [ericmdantas/generator-ng-fullstack#59]
After generating the code and starting with 
"node start" I get an error stating that "node index" command failed. Starting with "node index" by myself I get an syntax in index.js (see below). I think it has to do with the "=>" sign that cannot be resolved.

/Users/thomasmundt/projects/tests/ng-fs-test/node_modules/babel-core/lib/transformation/file/index.js:671
      throw err;
      ^

SyntaxError: /Users/thomasmundt/projects/tests/ng-fs-test/server/api/todo/dao/todo.dao.js: Unexpected token (18:6)
  16 |                   : resolve(todos);
  17 |           });
> 18 |       );
     |       ^
  19 | }
  20 | 
  21 | todoSchema.statics.createTodo = (todo) => {
    at Parser.pp.raise (/Users/thomasmundt/projects/tests/ng-fs-test/node_modules/babylon/lib/parser/location.js:24:13)

**Comment by ericmdantas** [comment]
Hello, @tmundt.

Do you have babel installed? If so, what version are you using?

**Comment by tmundt** [comment]
Yes babel is installed globally:

$ npm -g list babel
/usr/local/lib
└── babel@6.3.13

Does your package work only with specific versions of NODE/npm?

**Comment by ericmdantas** [comment]
Yep, Node 4+, which will have the arrow function and many other stuff from ES6.

I'll doc it somewhere.

**Comment by tmundt** [comment]
I use 4.2.3. But do you have an idea why I do get those errors?
Am 16.12.2015 14:13 schrieb "Eric Mendes Dantas" <notifications@github.com>:

**Comment by tmundt** [comment]
I installed all from the scratch, but when I use npm start I am getting this (after typing http://localhost:3333 into my browser):

Pegasus:ng-fs-test2 thomasmundt$ node index
body-parser deprecated bodyParser: use individual json/urlencoded middlewares server/config/routes.conf.js:41:57
body-parser deprecated undefined extended: provide extended option node_modules/body-parser/index.js:105:29
up and running @: Pegasus.local on port: 3333
enviroment: undefined
events.js:142
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/Users/thomasmundt/projects/tests/ng-fs-test2/client/__tmp/index.html'
    at Error (native)

**Comment by ericmdantas** [comment]
Oh, that one you'd have to run:

```
gulp
```

and then

```
npm start
```

Like said in the wiki: https://github.com/ericmdantas/generator-ng-fullstack/wiki/node#getting-started

For 1.6 I'm removing the `__tmp` folder, there'll be only `dev` and `dist`.
