### ISSUE TITLE
Use same folder structure for client projects

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#63]
Define if it's going to be a deep tree, like in:

```
client
  dev
    todo      
      components
        todo_cmp.ts
      services
        todo_service.ts
      styles     
        todo.css
      templates      
        todo.html
```

or something flat, like in:

``` 
client
  dev
    todo
      todo.html
      todo.css
      todo_cmp.ts
      todo_service.ts
``` 

PS:

Remember that there'll be an option to make tests side by side with the source code, turning the structure into:

```
client
  dev
    todo      
      components
        todo_cmp.ts
        todo_cmp_test.ts
      services
        todo_service.ts
        todo_service_test.ts
      styles     
        todo.css
      templates      
        todo.html
```

``` 
client
  dev
    todo
      todo.html
      todo.css
      todo_cmp.ts
      todo_cmp_test.ts
      todo_service.ts
      todo_service_test.ts
```

**Comment by Toub** [comment]
This is definitely the recommended way to go:

client
  dev
    todo
      todo.html
      todo.css
      todo_cmp.ts
      todo_cmp_test.ts
      todo_service.ts
      todo_service_test.ts

https://docs.google.com/document/d/1XXMvReO8-Awi1EZXAXS4PzDzdNvV6pGcuaF4Q9821Es/mobilebasic?pli=1

And if your module has too many components, you can create sub-folders by sub-module (not by type).

**Comment by ericmdantas** [comment]
Thanks for the link, I saw it once and then couldn't find it again :+1:

**Comment by Toub** [comment]
You might also be interested about this [angular2-style-guide](https://github.com/mgechev/angular2-style-guide).

**Comment by ericmdantas** [comment]
Definitely! Thanks!

**Comment by ericmdantas** [comment]
The structure is the following:

```
client
  dev
    todo      
      components
        todo_cmp.ts
      services
        todo_service.ts
      styles     
        todo.css
      templates      
        todo.html
```
