### ISSUE TITLE
can't start server

### ISSUE THREAD

**Issue by victorhazbun87** [ericmdantas/generator-ng-fullstack#65]
npm start

> fullstack@0.0.1 start /Users/victor/projects/fullstack
> node index

module.js:328
    throw err;
    ^

Error: Cannot find module './server/server'

What is going on? I followed all the steps in the wiki.

Then when changing the index.js

require('./server/server.ts');

I get another error: 

> fullstack@0.0.1 start /Users/victor/projects/fullstack
> node index

/Users/victor/projects/fullstack/server/server.ts:10
import * as express from 'express';
^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)

**Comment by ericmdantas** [comment]
Hello, @victorhazbun87.

I guess that should be: 

```
$ gulp 
```

```
$ tsc 
```

```
$ npm start
```
