### ISSUE TITLE
Reorganize the wiki

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#67]

**Comment by ericmdantas** [comment]
Maybe merge it back to the Readme?

**Comment by georgeedwards** [comment]
A "Getting Started" tutorial type walk-through of building a super-simple web app with this generator would also be really helpful. (speaking as someone evaluating different generators)

**Comment by ericmdantas** [comment]
Good idea, @georgeedwards! I might do that for all the combinations of options, like ng1 + nodejs, ng2 + go, etc.

**Comment by georgeedwards** [comment]
@ericmdantas That would be great! I have sent you an email, I am happy to help writing up some docs if you would like, let me know if you get it.

**Comment by ericmdantas** [comment]
@georgeedwards Sure! I'd love some help.

Just responded the email, by the way. See if there's something else you'd like to know.

**Comment by georgeedwards** [comment]
Awesome, well I think this will be ongoing, first lot done...

**Comment by ericmdantas** [comment]
Closing this, if you feel like opening a new issue to track/document specific content, feel free to do so :smile:
