### ISSUE TITLE
Fix typings for typescript server

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#79]
~~Angular2 (src and test)~~
- Typescript Server

**Comment by ericmdantas** [comment]
Maybe adding both  'typings/main.d.ts' and 'node_modules/angular2/typings/browser.d.ts' to tsconfig.json?

**Comment by ericmdantas** [comment]
Client side done.

Server left.

**Comment by fklingler** [comment]
Any news on this issue? I'm really interested on the TS server.

It seems that the typings are first generated in the `server` directory, but if you use `typings install` command, it installs the typings at the root. Is it normal?

**Comment by ericmdantas** [comment]
Hello, @fklingler.

The correct `typings` is the one in the root, the one in the server folder can be ignored by now - I'll remove it later.

And yes, I'm trying to solve this before `1.6` stable is released.

**Comment by ericmdantas** [comment]
Latest node typings has got some errors: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/8514

**Comment by fklingler** [comment]
Thanks for this.

I experimented a little, and it seems that there is no need to add the reference to the typings in each file. You should just include the typings file to TSC:

_build_tsc.js_
```js
import gulp from 'gulp';
import tsc from 'gulp-typescript';

gulp.task('server.compile_tsc', () => {
  return gulp.src(['server/**/*.ts', '!node_modules/**', 'typings/main.d.ts'],  {base: "./"})
             .pipe(tsc({}))
             .pipe(gulp.dest('./'));
});
```

**Comment by ericmdantas** [comment]
Yeah, I had forgotten about it. 

I removed those, did more changes to make the typescript server run smoothly, but looks like there are some stuff that it's not my fault, it's more like `tsd` and `typings` fighting each other - and not being compatible some times.

Yesterday I released 1.6.0 with these changes, there's more to be done, but we're closer to get this fixed.

**Comment by ericmdantas** [comment]
@Dev-Force any other errors happening here? Or can we close this?

**Comment by Dev-Force** [comment]
umm i think the content length is still here

**Comment by ericmdantas** [comment]
Yup, I'll do it tomorrow so we can close this.

**Comment by Dev-Force** [comment]
perfect, gn then
