### ISSUE TITLE
Getting Errors in gulp when running the app.

### ISSUE THREAD

**Issue by daimz** [ericmdantas/generator-ng-fullstack#82]
I have done a fresh install of the generator and then run `npm start` and `gulp` I originally was unable to get NPM to start but solved that by using the suggestion [here](https://github.com/ericmdantas/generator-ng-fullstack/issues/68#issuecomment-179803343) which at least allowed me to launch the app.

The problem however is when I run `gulp` I can see the following and nothing happens when I save files:

`[23:09:41] Requiring external module babel-register
[23:09:42] Using gulpfile ~/Sites/BudgetApp/gulpfile.babel.js
[23:09:42] Starting 'client.build_ts:dev'...
[23:09:42] Starting 'client.browser_sync'...
[23:09:42] Finished 'client.browser_sync' after 233 μs
server/api/todo/controller/todo-controller.ts(8,10): error TS2339: Property 'getAll' does not exist on type 'Model<Document>'.
server/api/todo/controller/todo-controller.ts(9,28): error TS2339: Property 'status' does not exist on type 'Object'.
server/api/todo/controller/todo-controller.ts(10,29): error TS2339: Property 'status' does not exist on type 'Object'.
server/api/todo/controller/todo-controller.ts(14,23): error TS2339: Property 'body' does not exist on type 'Object'.
server/api/todo/controller/todo-controller.ts(17,10): error TS2339: Property 'createTodo' does not exist on type 'Model<Document>'.
server/api/todo/controller/todo-controller.ts(18,27): error TS2339: Property 'status' does not exist on type 'Object'.
server/api/todo/controller/todo-controller.ts(19,29): error TS2339: Property 'status' does not exist on type 'Object'.
server/api/todo/controller/todo-controller.ts(23,19): error TS2339: Property 'params' does not exist on type 'Object'.
server/api/todo/controller/todo-controller.ts(26,8): error TS2339: Property 'deleteTodo' does not exist on type 'Model<Document>'.
server/api/todo/controller/todo-controller.ts(27,23): error TS2339: Property 'status' does not exist on type 'Object'.
server/api/todo/controller/todo-controller.ts(28,27): error TS2339: Property 'status' does not exist on type 'Object'.
server/api/todo/dao/todo-dao.ts(4,23): error TS2307: Cannot find module 'bluebird'.
server/api/todo/model/todo-model.ts(10,16): error TS2348: Value of type 'typeof Schema' is not callable. Did you mean to include 'new'?
server/config/db.conf.ts(6,26): error TS2307: Cannot find module '../constants/db.json'.
server/config/routes.conf.ts(5,25): error TS2307: Cannot find module 'morgan'.
server/config/routes.conf.ts(6,29): error TS2307: Cannot find module 'body-parser'.
server/config/routes.conf.ts(7,32): error TS2307: Cannot find module 'express-content-length-validator'.
server/config/routes.conf.ts(8,25): error TS2307: Cannot find module 'helmet'.
server/config/routes.conf.ts(15,21): error TS2339: Property 'use' does not exist on type 'Object'.
server/config/routes.conf.ts(15,29): error TS2339: Property 'static' does not exist on type 'Object'.
server/config/routes.conf.ts(16,21): error TS2339: Property 'use' does not exist on type 'Object'.
server/config/routes.conf.ts(16,29): error TS2339: Property 'static' does not exist on type 'Object'.
server/config/routes.conf.ts(17,21): error TS2339: Property 'use' does not exist on type 'Object'.
server/config/routes.conf.ts(18,21): error TS2339: Property 'use' does not exist on type 'Object'.
server/config/routes.conf.ts(19,21): error TS2339: Property 'use' does not exist on type 'Object'.
server/config/routes.conf.ts(20,21): error TS2339: Property 'use' does not exist on type 'Object'.
server/routes/index.ts(11,9): error TS2339: Property 'route' does not exist on type 'Object'.
server/routes/index.ts(14,10): error TS2339: Property 'use' does not exist on type 'Object'.
tests/client/todo/components/todo-cmp_test.ts(28,23): error TS2307: Cannot find module '../client/dev/todo/todo_cmp.js'.
tests/client/todo/components/todo-cmp_test.ts(29,27): error TS2307: Cannot find module '../client/dev/todo/todo_service.js'.
tests/client/todo/services/todo-service_test.ts(9,27): error TS2307: Cannot find module '../client/dev/todo/todo_service'.
[23:09:45] TypeScript: 31 semantic errors
[23:09:45] TypeScript: emit succeeded (with errors)
[23:09:45] Finished 'client.build_ts:dev' after 2.87 s
[23:09:45] Starting 'client.watch'...
[23:09:45] Finished 'client.watch' after 29 ms
[23:09:45] Starting 'default'...
[23:09:45] Finished 'default' after 16 μs
[BS] Proxying: http://localhost:3333
[BS] Access URLs:`

Any ideas as to what might be happening?

**Comment by ericmdantas** [comment]
Hello, @daimz.

The typings error is a known issue and are being tracked [here](#79) and [here](#68).

As for the gulp task not running when files are changed, that's a different issue. I'll close this one and open an issue for the `watchable` files not being updated. For the typings, you can follow the issues above.

Thanks!

**Comment by daimz** [comment]
Thanks @ericmdantas! 
Noticed the links you added don't work btw.

**Comment by ericmdantas** [comment]
Oops, updated :smile:
