### ISSUE TITLE
The style's generator is been creating the css file with the wrong content (html structure)

### ISSUE THREAD

**Issue by bernardbr** [ericmdantas/generator-ng-fullstack#86]
Try:
`$ yo ng-fullstack:style icia-cara --feature mais_que_del`

and the default content of file " client\dev\mais_que_del\styles\icia-cara.css" will be:

`<h1>
  my new view :D - it's called icia-cara
</h1>
`

**Comment by ericmdantas** [comment]
That's a bug with `1.6.0-12`, I'll release `1.6.0-13` tonight.

**Comment by ericmdantas** [comment]
Fixed.
