### ISSUE TITLE
deprecated gulp-minify-css

### ISSUE THREAD

**Issue by georgeedwards** [ericmdantas/generator-ng-fullstack#89]
Current Sample App when configured like this:
FullStack, node, ng2, Typescript
and installed on windows throws this error:

    npm WARN deprecated gulp-minify-css@0.4.6: Please use gulp-clean-css
    npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
    npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
    npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
    npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm
    npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

Not looked into this at all, but I expect it affects every configuration? I will have a look and submit a PR in next couple of days unless there is any major complication...

**Comment by ericmdantas** [comment]
The only generator's direct deps are `gulp-minify-css` and `lodash`. The others, I'm pretty sure are deps of the deps, so there's not much we can do.

Other than that, go for it!

**Comment by ericmdantas** [comment]
Can we close this or you're taking a look at the others too?

**Comment by georgeedwards** [comment]
Let's close it, but I might come back to them.

**Comment by ericmdantas** [comment]
Cool.
