### ISSUE TITLE
Add router subgenerator (AngularJS 1.4)

### ISSUE THREAD

**Issue by ericmdantas** [ericmdantas/generator-ng-fullstack#9]
As soon as AngularJS 1.4 is out (stable), release a version with the new router and a subgenerator for such.

**Comment by honkskillet** [comment]
Will this be an angular 1.x stack?  I thought it was going to be a 2 stack.

**Comment by ericmdantas** [comment]
It's an angular latest stable version stack.

The next one to come is 1.4, as soon as 2.0 is out, I'll make sure it's a 2.0 stack.
