### ISSUE TITLE
heroku api issue 

### ISSUE THREAD

**Issue by itranga** [ericmdantas/generator-ng-fullstack#97]
I hosted sample app in https://mytemple.herokuapp.com/ . I got following issue in console .

https://mytemple.herokuapp.com/api/todos/ 503 (Service Unavailable).

I connected mongodb in  mongolab

**Comment by ericmdantas** [comment]
Hello, @itranga.

Did you change the MONGOHQ_URL to MONGOLAB? https://github.com/ericmdantas/generator-ng-fullstack/blob/master/app/templates/server_node/config/db.conf.js#L8

**Comment by itranga** [comment]
Yes . I have change it in db.json file . 

"localhost": "mongodb://username:pwd@ds031952.mlab.com:31952/temple"

My local app is working fine .I have issue only in heroku server.I think it have some issue in api url .

**Comment by ericmdantas** [comment]
What's the content of your `procfile.txt`?

**Comment by itranga** [comment]
I have allready done . 
procfile = web: npm start

**Comment by ericmdantas** [comment]
Same error?

If so, is the deploy to heroku ok or there are some errors? Also, can you connect to the DB outside of the application?

**Comment by itranga** [comment]
I got the same error . I connected MONGO Db from https://mlab.com/  . I think issue is in router . Because I try to view https://mytemple.herokuapp.com/api/todos/. it's not working .But my local pc app router is working [ http://localhost:3333/api/todos ]

**Comment by ericmdantas** [comment]
Can you show some logs/prints?

**Comment by itranga** [comment]
Online

https://mytemple.herokuapp.com/api/todos/

Chrome Print

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

Offline 

http://localhost:3333/api/todos/

Chrome Print

[{"_id":"56f49f682f31c84360a6c018","todoMessage":"test","__v":0,"createdAt":"2016-03-25T02:16:08.587Z"},{"_id":"56f4a399a1bfc50d6435f672","todoMessage":"test2","__v":0,"createdAt":"2016-03-25T02:34:01.606Z"},{"_id":"56f4e8a2d14e76e01d4220bc","todoMessage":"ssdsd","__v":0,"createdAt":"2016-03-25T07:28:34.074Z"},{"_id":"56f77003d256cfdb04d6be26","todoMessage":"ranga","__v":0,"createdAt":"2016-03-27T05:30:43.903Z"}]

**Comment by ericmdantas** [comment]
I see, the page is showing, but there's no interaction with the server.

The thing I'm noticing is the request is taking forever to resolve. For example, the `GET` on `api/todos` took `1min` and then got the `503 Service Unavailable` error. 

Are you using `express` to serve the `index.html` or some static server? If you're not using express, make sure your proxy is set up correctly.

**Comment by itranga** [comment]
I used your generator-ng-fullstack code .change only db.json file .

**Comment by ericmdantas** [comment]
You'll also have to change the enviroment variable.

By default, the generator uses `MONGOHQ_URL` to connect to the database. You'll have to use `MONGOLAB_URI`. That config is in `server/config/db.config.js`.

**Comment by itranga** [comment]
I have change MONGOHQ_URL to MONGOLAB_URI . Did u try to host your code heroku servers ?

**Comment by ericmdantas** [comment]
Yes - it's been a while, though.

Let me give it a try with a newer version.

**Comment by ericmdantas** [comment]
Alright, got it to work with mongolab: https://issue-97.herokuapp.com/

What I had to do:

- Set up the config for mongolab, create db name, user and password;
- Go to Heroku and add the addon for MongoLab;
- Also in Heroku, create the NODE_ENV variable and set it to `production`;
- Still in Heroku, change the MONGOLAB_URI to your db uri located in mongolab;
- The only file you have to change in the generator is in `server/config/db.conf.js`, change from `MONGOHQ_URL` to `MONGOLAB_URI`.

The rest is just the default Heroku deploy steps.

https://devcenter.heroku.com/articles/git

**Comment by itranga** [comment]
Thank you so much for all you have done for me . I will follow your process

**Comment by ericmdantas** [comment]
Thanks for sticking by, and providing some feedback on how to reproduce it :smile:

**Comment by ericmdantas** [comment]
By the way, I created an explanation in the wiki to help other people that might run into similar problems: https://github.com/ericmdantas/generator-ng-fullstack/wiki/Deploying-to-Heroku

**Comment by itranga** [comment]
it's working now . I changed const URL = dbConst.localhost; in db.conf.ts .  (Because Need to add Credit card to create mLab MongoDB in heroku  ) 

I want again to thanks you for help and support

http://mytemple.herokuapp.com/

**Comment by ericmdantas** [comment]
Awesome! :+1:
